### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by zedtux** [raycast/script-commands#10]
Obviously, having this on Linux would be just *the most amazing tool* in its category.

It looks like it is 100% macOS only but Github show it has most of the code is Swift code and Swift is now open source so maybe that make supporting Linux an option? 🙏 

Anyways, great tool guys, really awesome.

**Comment by thomaspaulmann** [comment]
Hey @zedtux,

Raycast only supports macOS right now. We want to nail the experience on the Apple platform first. Eventually we will expand to Linux and other operating systems. This will not happen in the near-term future. Because Script Commands are a feature of Raycast, this is blocked on it. I'll close this issue to avoid any confusions. 

Best,
Thomas

**Comment by zedtux** [comment]
I see ... hopefully Linux support will be quite soon, we really miss it!

**Comment by sheldonhull** [comment]
Is there any article on the differences in the macOS and Linux architecture that explains why linux/macOS aren't possible at the same time? I'm curious as I've migrated my home system to Ubuntu, and use macOS for work. I've missed raycast :-)

**Comment by amitmerchant1990** [comment]
I want it on my Linux as well.

**Comment by Notaduck** [comment]
Same her, I love abselutley love raycast for mac, and if we could get 8/10 of the features for linux that would be a blast!

**Comment by koalazub** [comment]
Any updates on this? Would be keen to know for down the track

**Comment by joaomendoncaa** [comment]
Think that at this point the code might be so entrenched in Metal's API that it will be a huge effort to port it without much return for the startup.

Guess I'll have to do it myself.

**Comment by gustavo-fior** [comment]
Raycast in Linux would be amazing :/
