### ISSUE TITLE
Custom parameters are not working correctly.

### ISSUE THREAD

**Issue by joe-zhang3** [raycast/script-commands#108]
Using below scripts:

```sh
#!/bin/bash

# Raycast Script Command Template
#
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Launch V2
# @raycast.mode silent

# Optional parameters:
# @raycast.packageName v2
# @raycast.argument1 { "type": "text", "placeholder": "mode" }

./startup.sh ${1}
```

Problems:

1. Above snippet was copied from the instruction page, but those `optional parameters` are not `optional`. I got a `Value is missing in argument` popup when I leave the parameter blank. So how to specify an really `optional` parameter?

2. Choose the script command, specify the parameter, hit enter, it works like a charm. But next time if I use hotkey to call Raycast out again, the script command I used before is automatically selected and the parameter filed gets the focus even I don't want to use the script command again. I cannot navigate to whatever I want as I need to get the cursor out of the parameter field first, either by using cursor clicking or use tab. 

EXPECTED:
Everything should be cleared ever time when Raycast gets called out.

**Comment by crstauf** [comment]
1. Optional parameters are not currently supported.

2. This functionality has been mentioned a couple of times in Slack, and is being worked on; apparently there are situations where you may not want Raycast to start at root.

**Comment by fe9lix** [comment]
Hi @joe-zhang3! Optional parameters here means that the @raycast argument parameter itself is optional in the metadata. Regarding 2) It's a known bug and will be fixed in the next release.

**Comment by PitNikola** [comment]
Re: 1) optional arguments

We're planning to add support for optional arguments.
