### ISSUE TITLE
Missing error messages for command scripts when missing dependencies

### ISSUE THREAD

**Issue by grzegorzkrukowski** [raycast/script-commands#119]
I found out that error handling for some commands that may miss dependencies or fail due to wrong parameters, like `gpg`, `pa11y`, `shorten-url` is not working properly.
Instead of showing error message that is desired and defined in script, Raycast is closing itself, crashing.
After reopening Raycast again there is `"Script failed to run"` information being shown at the very bottom.

Please find screenshot attached:

<img width="733" alt="Screenshot 2020-11-28 at 13 20 55" src="https://user-images.githubusercontent.com/1301068/100515559-5912a800-317d-11eb-9af4-235b420fd6f1.png">

**Steps to reproduce:**
1. Install https://github.com/raycast/script-commands/blob/master/commands/developer-utils/generate-password.sh command
2. Make sure `gpg` is not installed
3. Execute `generate password command`
4. See Raycast crashing without any information for user
5. Launch Raycast again to see `Script failed to run` information that disappears after a while

**Expected behaviour**
1. When executing `generate password` command without `gpg` there should be readable message shown for a user, which is already part of the script, but now shown properly: `"gpg command is required (https://www.gnupg.org/)."`

**Fix**
When using `exit 0` instead of `exit 1` things are getting back to normal.

Guidelines https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md are also suggesting to use `exit 1` in scripts - so I think that Raycast needs to handle it properly.

I originally tried to fix it with `if/else` or `exit 0` approach and created a PR for that to fix scripts - but after going deeper into Guidelines I am sure it has to be fixed inside Raycast code to be in line with Guidelines.

**Comment by crstauf** [comment]
Yeah, this was discussed elsewhere (in Slack or another PR) and is on the Raycast team's radar to address. 

Centralizing the convo on this issue will be helpful.

**Comment by PitNikola** [comment]
Thanks for reporting it @grzegorzkrukowski. That indeed seems like a bug from our side. We'll take a look into it.

**Comment by PitNikola** [comment]
This should be resolved in `v1.3.0`.
