### ISSUE TITLE
Accept arguments

### ISSUE THREAD

**Issue by tborychowski** [raycast/script-commands#12]
Thanks for this amazing app!
It's the best thing that happened to my mac since Alfred (10 years ago)!

It would be fantastic if a script could accept arguments, e.g.:
- I'd like to search npmjs.com for a module
- I'd like to create a script called `npm` that I run like so: `npm lodash` - which opens url: `https://www.npmjs.com/search?q=lodash`

Current problems:
- typing script title and something else - just shows File, google & duckduckgo searches.

Alternatively - you could allow custom searchers (so e.g. npm, stackoverflow, github could be added), but the former would give users more power :-)

**Comment by thomaspaulmann** [comment]
We're gonna look into this. Thanks for the suggestion.

**Comment by u12206050** [comment]
Would love to be able to execute Laravel Artisan commands. Am able to add the artisan command as a cast but since it doesn't accept arguments it isn't really worth much.

An issue I do wonder about is long running commands eg. `npm run dev` if I were to create a compact cast for this command how would I go about stopping it?

**Comment by krawitzzZ** [comment]
+1 here! would really like to have this feature. in my eyes it looks like this:
1. you press tab while your custom script is selected (like it is with clipboard history)
2. you see the prompt where you could type something
3. you press return and script gets executed with whatever was provided as an argument
:)

**Comment by NikoManiac** [comment]
+1, I have save problem. I hope my custom script can accept arguments too.

**Comment by PitNikola** [comment]
Quick update on this one: the implementation for this feature is in progress.

**Comment by PitNikola** [comment]
Support for arguments is now added in v1.2.0, see [Passing Arguments](https://github.com/raycast/script-commands#passing-arguments) section for more details.

We also added a separate folder for [web searches](https://github.com/raycast/script-commands/tree/master/commands/web-searches). @tborychowski, feel free to create PR for npm search 😉

**Comment by tborychowski** [comment]
Thanks @PitNikola!
That works great and opens up a world of customizations! :-)
Here's the PR for npm: https://github.com/raycast/script-commands/pull/89

**Comment by danielo515** [comment]
Do arguments work for bash scripts? I am using a very basic config,and I am not getting any argument in the prompt
