### ISSUE TITLE
Is there any template/example script written with JS?

### ISSUE THREAD

**Issue by aesign** [raycast/script-commands#129]

**Comment by unnamedd** [comment]
Hi @aesign, 

Yes, there is, but no here only in Slack. Are you there? If yes, you can use this [link](https://raycastcommunity.slack.com/archives/C01D1B36344/p1606184353370400) to see an example.

**Comment by aesign** [comment]
Thanks, I just joined the channel and downloaded the files. Anyway, the script doesn't come up inside the Extensions tab. Any idea why?

**Comment by unnamedd** [comment]
You need to add it into some folder you prefer and that folder in the Extensions > Script Commands. If it continue to not appear in the list of Script Commands, you will have to set it as executable. To do this, navigate to the folder where you saved the script command and type: `chmod +x name-of-that-script-command.js`.

**Comment by aesign** [comment]
The command did it! Thank you!
