### ISSUE TITLE
Use website favicon for Wayback Machine Search

### ISSUE THREAD

**Issue by crstauf** [raycast/script-commands#134]
@mrmartineau Is there any issue with using [the icon used](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/images/ia-logo.jpg) for [the "Save to Wayback Machine" script](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/wayback-machine-save.sh) for the "Wayback Machine search" script's icon as well?

**Comment by mrmartineau** [comment]
@crstauf no issues at all, go for it
