### ISSUE TITLE
imessage-2fa regular expressions do not support Google 2FA

### ISSUE THREAD

**Issue by crstauf** [raycast/script-commands#136]
While the regex for [the `imessage-2fa` script](https://github.com/raycast/script-commands/blob/master/commands/communication/imessage-2fa.sh) identifies and isolates 2FA codes (large numbers) sufficiently for most services, it doesn't handle 2FA codes that are preceded with character, ex: Google (`G-123456`). 

The regex should be adjusted to keep current working functionality, and also identify and isolate 2FA codes from Google (and others) that precede the 2FA code with a single letter and dash (ex: `G-`).

There are multiple regular expressions in use:
- [database query](https://github.com/raycast/script-commands/blob/master/commands/communication/imessage-2fa.sh#L42-L45)
- [extract from text message](https://github.com/raycast/script-commands/blob/master/commands/communication/imessage-2fa.sh#L21)

**Comment by PitNikola** [comment]
@crstauf, is it still relevant? I was wondering if we can close this issue due to inactivity.

**Comment by crstauf** [comment]
@PitNikola it is relevant. I created the issue so that people would be aware and pick it up. Closing it prior to being addressed would significantly reduce visibility.

**Comment by grzegorzkrukowski** [comment]
Hey @crstauf I just tried the latest version of this script and it works just fine for me. At least `G-1` format seems to be covered with regexps that you are pointing to.

Do you have some examples that are not working still ?

**Comment by crstauf** [comment]
I will run some checks tomorrow to make sure, but pretty sure not supported.

**Comment by crstauf** [comment]
Okay so it does seem that the codes preceded with a dash do work, but not codes preceded with a letter. I can't recall which service does that, but I have seen a 2FA code with a preceding letter. Given how obscure and rare that is, this issue can be closed and the "help wanted" label removed.
