### ISSUE TITLE
Access to more advanced UI elements?

### ISSUE THREAD

**Issue by jkelleyrtp** [raycast/script-commands#153]
Haven't found this anywhere - how I would I go about adding a custom script that renders more advanced UI elements?

One example being the filter + list of the github application.

**Comment by thomaspaulmann** [comment]
Hey @jkelleyrtp, this sounds like something for our API that is under development. You can read more about it here: https://raycast.com/developer-program

I'll close this issue because this is something that isn't part of script commands.

**Comment by jeasonstudio** [comment]
@thomaspaulmann When can we use this 'developer program'?

**Comment by PitNikola** [comment]
Probably you've already discovered it yourself by this moment, but just for the record if anybody stumbles upon this issue – here's new [extensions](https://github.com/raycast/extensions) repo. Now you can build more complex extensions using JS/TS and React.
