### ISSUE TITLE
AppleScript Command Runs Slowly

### ISSUE THREAD

**Issue by pacocoursey** [raycast/script-commands#163]
I'm using this AppleScript to toggle an application's visibility:

<details>

<summary>Script</summary>

<pre>
#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle Visual Studio Code
# @raycast.mode compact
#
# Documentation:
# @raycast.description Toggle Visual Studio Code App
# @raycast.author paco
# @raycast.authorURL paco.sh

set appName to "Visual Studio Code"
set startIt to false
tell application "System Events"
	if not (exists process appName) then
		set startIt to true
	else if frontmost of process appName then
		set visible of process appName to false
	else
		set frontmost of process appName to true
	end if
end tell
if startIt then
	tell application appName to activate
end if
</pre>
</details>

But sometimes it takes upwards of 5 seconds to run! Is this an issue with my script or Raycast? Why is it so slow? Are there plans to add this functionality to Raycast natively (like Alfred has it as a built-in workflow action)?

**Comment by thomaspaulmann** [comment]
Hey @pacocoursey,

Thanks for reporting the performance issue and attaching a script. I couldn't reproduce it on my machine but it could be related to the check for an existing process. Depending on the amount of running processes, this check can vary. I took an attempt to remove the call and the following script seems to work fine for me. Could you give it a try please?

```AppleScript
#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle Visual Studio Code
# @raycast.mode silent
#
# Documentation:
# @raycast.description Toggle Visual Studio Code App
# @raycast.author paco
# @raycast.authorURL paco.sh

set applicationName to "Code"

if application applicationName is running then
  tell application "System Events"
    if frontmost of application process applicationName then
      set visible of application process applicationName to false
    else
      set frontmost of application process applicationName to true
    end if
  end tell
else
  tell application applicationName to activate
end if
```

We could add the the toggling as an action to the action panel similar as we have quit and force quit actions for the running applications. Would that work for you? Any suggestion for a keyboard shortcut for the action?

**Comment by pacocoursey** [comment]
Thanks @thomaspaulmann, your script does seem to run much faster! (maybe something related to the name of application being "Code" instead of "Visual Studio Code"? Not sure)

> We could add the the toggling as an action to the action panel similar as we have quit and force quit actions for the running applications

I wouldn't find this too useful – my main motivation is to assign a Global Hotkey to these toggle actions so that I can jump between applications with just my keyboard. (Cmd+Shift+Enter to go to VSCode, Cmd+Shift+S to go to Slack, etc.)

Ideally this would be an entry under the "System" extension, but instead of a toggle you could have a list of applications you want to be able to toggle. Then I could add Slack, and assign a Global Hotkey to the "Toggle Slack Application" action.

**Comment by pacocoursey** [comment]
Not sure I totally understood this comment:
> we have quit and force quit actions for the running applications

Where can I find this behavior? I don't see it on Raycast search or the commands [here](https://github.com/raycast/script-commands/tree/master/commands)

**Comment by thomaspaulmann** [comment]
> My main motivation is to assign a Global Hotkey to these toggle actions so that I can jump between applications with just my keyboard. (Cmd+Shift+Enter to go to VSCode, Cmd+Shift+S to go to Slack, etc.)

Actually, if it's just about jumping between applications with global hotkeys, this is already possible! Go to Raycast Preferences > Shortcuts, then add your apps and assign hotkeys. It doesn't toggle the app but it launches the app or brings it to the foreground.

![CleanShot 2020-12-10 at 11 59 59@2x](https://user-images.githubusercontent.com/12066405/101844235-dc4fd880-3b43-11eb-98e3-9f5275cace8a.png)

> Where can I find this behavior? I don't see it on Raycast search or the commands here

You can find additional actions when you have an app selected in the root search and hit Command-K:

<img width="933" alt="CleanShot 2020-12-10 at 11 58 30@2x" src="https://user-images.githubusercontent.com/12066405/101844127-9eeb4b00-3b43-11eb-84d3-b6de2e79be8d.png">

I hope that helps.

**Comment by pacocoursey** [comment]
Wow, can't believe I missed that! That totally solves my use case, so I'll close this issue. Thanks a ton!

**Comment by thomaspaulmann** [comment]
To be fair, we've just shipped this feature a couple of hours ago. So, good timing I guess 🤣 I'm glad we can support it out of the box!
