### ISSUE TITLE
node: command not found

### ISSUE THREAD

**Issue by dawidjaniga** [raycast/script-commands#165]
**Problem**
I can't execute executable script.sh which uses _node_ via Raycast. Running the same script from CLI _./script.sh_ works correctly.

**Output**
```
/Users/user/Documents/raycast-scripts/script.sh: line 11: line 11: node: command not found
```

**Expected**
node is in my $PATH so I can run scripts via Raycast the same way I run them from CLI.

**script.sh*(
```
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open Script
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.packageName Applications

node script.js
```
script.js is also executable

**Comment by thomaspaulmann** [comment]
This is expected. The script is executed in a [non-login shell](https://github.com/raycast/script-commands#login-shell-and-path). Therefore the `node` command from your `$PATH` isn't loaded. You can either append `-l` to your shebang or just use the `script.js` directly as your script. [Here](https://github.com/raycast/script-commands/blob/master/templates/script-command.template.js) is an example on how to use `Node` from Raycast.

**Comment by dawidjaniga** [comment]
If this is expected something weird happen :D Script written by me on one MacBook work correctly (without -l, bash script as shown above), but on other Mac the problem occurred. Unfortunately adding -l didn't resolve the problem, using Node directly either. Do you have some idea how to make it work?
Thanks 👍

**Comment by unnamedd** [comment]
@dawidjaniga if `node` is installed only for your user, then Raycast won’t be able to find it. `node` will be need to be accessed Bia `/usr/bin/node`, if it is not there, you may have to add or install it globally.

**Comment by dawidjaniga** [comment]
Thank you @unnamedd
You're right and the problem was indeed in Node.js installation path. I will leave the solution for reference:

I use *n* node version manager. Node binary should be accessible not only for current user, but for entire machine. You can add path to *n* binaries as follows:
Copy path to node:
```
where node
```

For example: `/Users/username/n/bin`

```
sudo code /etc/paths
```
And add the node path.

**Comment by urre** [comment]
is there an example how do append -l to the shebang?

**Comment by tobbbe** [comment]
For future travelers: `#!/bin/bash -l` (lowercase L) made global npm package available in a raycast script

**Comment by xGreenNarae** [comment]
I'm using zsh and the -l option doesn't seem to be accepted. Also, the node path seems to keep changing depending on the version since I am using mise. How can I solve this problem?

**Comment by rmjohnson-olo** [comment]
@xGreenNarae I was able to use `source ~/.zshrc` before my commands to get the script to load my .zshrc file. This solved my problem of the Raycast script not having access to the same things I do in my regular terminal.
