### ISSUE TITLE
Disable Toast

### ISSUE THREAD

**Issue by Jax0rz** [raycast/script-commands#170]
How to disable this toast? I tried the silent mode.

![CleanShot 2020-12-29 at 18 15 02@2x](https://user-images.githubusercontent.com/7557357/103276587-eb6acd80-4a01-11eb-8b83-3fa90fedf256.png)

**Comment by PitNikola** [comment]
Is it AppleScript command? I suppose AppleScript logs something by default. Here's what you can do:
1. Add meaningful log message in the end of the script: for example `log "File was removed"` (depending on what your script does).
2. If you don't want to see the toast at all, then the workaround is to log empty string: `log ""`

Please let me know if that helped.

**Comment by Jax0rz** [comment]
> Is it AppleScript command? I suppose AppleScript logs something by default. Here's what you can do:
> 
> 1. Add meaningful log message in the end of the script: for example `log "File was removed"` (depending on what your script does).
> 2. If you don't want to see the toast at all, then the workaround is to log empty string: `log ""`
> 
> Please let me know if that helped.

Solved,Thanks.

```
tell application "Finder"
   set allDownloads to every item of folder (path to downloads folder as text)
   move allDownloads to trash
   log ""
end tell
```
