### ISSUE TITLE
Extract URL title

### ISSUE THREAD

**Issue by lkvnclh** [raycast/script-commands#181]
Can it be enhanced to extract the URL title as an option?
so the output can include both 
<title> + <ShortURL>
Thanks !

**Comment by unnamedd** [comment]
@lkvnclh you mean: extract the content of a html `<title></title>` tag from some specific URL?

**Comment by lkvnclh** [comment]
> @lkvnclh you mean: extract the content of a html `<title></title>` tag from some specific URL?

Yes
but I forgot to mention that I m actually referring the shoten-url script command 
[](https://github.com/raycast/script-commands/blob/master/commands/browsing/shorten-url.sh)

but it would be nice to offer such thing in Raycast as script-command.

**Comment by unnamedd** [comment]
@lkvnclh I guess I understood your point, but the problem I see in this approach (extract the content from `<title/>` tag) is: not every time the URL to be shorted might have html tags inside (may be a json, a xml, a rss as well), which might lead us to a problem and the script command as-is wasn't planned for that.

As this is not something related directly to anything else we can do at the moment, I will close this issue. If prefer to add anything else, I'd suggest to have a chat about it in our Slack channel [#script-commands](https://raycastcommunity.slack.com/archives/C01D1B36344). What do you think?
