### ISSUE TITLE
Error when toggling bluetooth with bluetooth-toggle.applescript

### ISSUE THREAD

**Issue by bdcarr** [raycast/script-commands#187]
When I run that command, it runs for a while before popping out an error:

![image](https://user-images.githubusercontent.com/1940488/104797457-437f3d80-5812-11eb-9ef5-ad11597356b6.png)

The full error can be seen when running the script via terminal:
```
./bluetooth-toggle.applescript:492:537: execution error: System Events got an error: Can’t get process "ControlCenter". (-1728)
```

MacOS 10.15.7 (19H114)

Tagging @vincentdoerig <3

**Comment by vincentdoerig** [comment]
What is your system language? If it is British English, the variable should be `ControlCentre`.

**Comment by bdcarr** [comment]
Ah yes, you're right. When I saw the note about system language, it didn't occur to me that 'Centre' is different in other versions of English.

Anyway, that didn't fix it, but I know why now:

![image](https://user-images.githubusercontent.com/1940488/104809851-73473900-5844-11eb-9b9a-3f61e1b24e93.png)

Looking forward to using this one when our IT dept lets us update to Big Sur!

**Comment by vincentdoerig** [comment]
Ah my bad, I totally forgot the control centre is new thing only available in Big Sur.
