### ISSUE TITLE
Calculator full number

### ISSUE THREAD

**Issue by ivanisko** [raycast/script-commands#218]
Hi guys,

first of all I want to thank you for great app.
Is there option how to get from calculator full number?

If I count this 496219,01 + 138172,17 I get 634,391k but full number is 634391.18

Thank you,

Jan

**Comment by unnamedd** [comment]
Hi @ivanisko,  

maybe what you want to have is the unformatted result, which you can get access the Actions in `⌘ + K` (Command + K) and selecting the option `Copy Unformatted Answer` (or pressing `⌘ + ⏎`).

![CleanShot 2021-02-04 at 13 03 24](https://user-images.githubusercontent.com/83694/106890319-6ef69900-66e9-11eb-8230-7c64d061d5f4.png)

Here is the result I copied: `634391,18`. 

Also, we would like to invite you to our [Community Slack](https://raycast.com/community). There is so far the best place for you to report bugs, bring suggestions or anything else you want.

For now, I will close this issue, but feel free to re-open if you have anything else to add here.
