### ISSUE TITLE
Apple Music "Current Track" doesn't work with streaming

### ISSUE THREAD

**Issue by MikeSuiter** [raycast/script-commands#221]
I've installed the Apple Music scripts on 2 2019 MacBook Pro's 15" with Big Sur 11.2, and don't know if these are issues or just the way they work.

1. When music is playing, "Current Track" just shows a Refreshed! snackbar and that's it. Is the snackbar supposed to show what is currently playing?
2. If I do a "Stop" and then a "Play" nothing happens. Maybe "Play" only works after a "Pause"?

### UPDATE
After some debugging with @unnamedd we found the problem with # 1 above is it only works with local songs. If you stream a song you get "Not playing". What happens is these two lines throw an error:

```AppleScript
		set currentTrackName to name of the current track
		set currentTrackArtist to artist of the current track
```

Labels
help wanted

**Comment by crstauf** [comment]
> 2. If I do a "Stop" and then a "Play" nothing happens. Maybe "Play" only works after a "Pause"?

That's correct.

**Comment by unnamedd** [comment]
@MikeSuiter as @crstauf already answered you, I guess we can close this issue. If you need anything else regarding this subject, feel free to reopen the issue or join us in our community: https://raycast.com/community, will be a pleasure to have you there.

**Comment by MikeSuiter** [comment]
@unnamedd What about #1 which hasn't been addressed? Looking at the script it's collecting the name and artist but all that happens is a refreshed snackbar.

**Comment by unnamedd** [comment]
@MikeSuiter here it's working well, check it out: 
![image](https://user-images.githubusercontent.com/83694/107118393-0d693280-6881-11eb-8d74-3e6eaf222387.png)
Reading the code, it update the dashboard each 10 seconds, then as soon you play a song or change it, it may take 10 seconds until refresh to present the current playing track.

**Comment by MikeSuiter** [comment]
@unnamedd Interesting just tried it on my wife's MBA M1 and it works fine. On my home MBP and work MBP it's not working even though play, pause, next, etc. are working from those scripts. Other than Music is there another permission current track needs?

**Comment by unnamedd** [comment]
I'm also using an M1 here. For sure, might be some permission missing. 
![CleanShot 2021-02-06 at 13 52 32](https://user-images.githubusercontent.com/83694/107118672-9765cb00-6882-11eb-9a63-b1bc9a591fbd.png)

I was checking my permissions and I unchecked the `Music` and it still here, working okay. Check in your configurations if you have gave permissions to Raycast to access your system across groups like Accessibility and Full Access Disk. It may be related to this.

**Comment by MikeSuiter** [comment]
Raycast has Full Disk Access and Accessibility access on my home MBP which doesn't have any company restrictions. 

<img width="862" alt="Screen Shot 2021-02-06 at 7 20 46 AM" src="https://user-images.githubusercontent.com/5289509/107119297-4e931f80-684c-11eb-87e1-a4c929429ab0.png">

**Comment by unnamedd** [comment]
@MikeSuiter, what happen when you try to run the script using the terminal? 
Here is my result:
```shell
$ cd script-commands/_enabled-commands/apple-music
$ osascript apple-music-current-track.applescript
A Tout Le Monde - Megadeth
```

**Comment by MikeSuiter** [comment]
```shell
> osascript apple-music-current-track.applescript
Not playing
```

I don't think it would matter, but my home MBP went from Mojave -> Catalina -> Big Sur and my wife's MBA M1 came with Big Sur. I'm using zsh and an admin on both.

**Comment by unnamedd** [comment]
@MikeSuiter, are you on our Slack? I guess we will be more productive solving that issue using a chat instead of the issue comments. What do you think?

**Comment by MikeSuiter** [comment]
@unnamedd I just joined the Raycast Slack? Should I post this in # bugs there?

**Comment by unnamedd** [comment]
I don't think this is a Raycast bug, this is related to your machine and me and you will try to solve this problem! ;)

Give some minutes to get back to my computer.

**Comment by MikeSuiter** [comment]
@mmerle since you're the author of this script I thought I would tag you. You can probably ignore all the replies here and just look at the UPDATE of the first post.
