### ISSUE TITLE
open path of currently selected file in iterm

### ISSUE THREAD

**Issue by rburgst** [raycast/script-commands#223]
Launchbar has a very useful feature where you can long hold CTRL Space and then it will copy the selected file as the launcher argument, when you then type "iTerm" it will launch the currently selected file in iterm. If the file is not executable it will simply open iterm in the containing folder. 
It would be very handy to have something similar in RayCast.

**Comment by mattisssa** [comment]
Hey @rburgst! Thank you very much for your suggestion. 
Could be a nice feature that needs to be supported, we will discuss it with our team!

Seems this question is unrelated to script commands, so I would recommend you to join our [Slack community](https://raycast.com/community) or use the in-app feedback form for such a suggestions 👍

**Comment by rburgst** [comment]
I was hoping to achieve that with a script. Such as 
1. get the selected item from finder
2. use that to invoke other actions
