### ISSUE TITLE
Ability to edit default search provier

### ISSUE THREAD

**Issue by chohner** [raycast/script-commands#225]
Is there a way to edit the default search provider?

Specifically, I want to remove google web search (and ideally move duckduckgo up).

**Comment by mattisssa** [comment]
Hey @chohner! 
There is no such feature for now, but we will discuss it with our team! 
Seems this question is unrelated to script commands, so I would recommend you to join our [Slack community](https://join.slack.com/t/raycastcommunity/shared_invite/zt-kqkibylu-t1pzzWlneQXd5I7W8AQFAQ) or use the in-app feedback form for such a suggestions 👍
