### ISSUE TITLE
Some system script-commands to not appear in the settings

### ISSUE THREAD

**Issue by tdeekens** [raycast/script-commands#227]
Hi,

thanks a lot for Raycast. It's incredible and I can't wait where you take it.

I recently noticed that there is a `audio-output-switch.template` which I'd love to use. I also saw it has the `title` `Switch Audio to <>`. However when adding the system `script-commands` to the Raycast settings I can't spot this command. Same for the Bluetooth command. 

Is there any trick to have it appear there?

Thanks.

**Comment by unnamedd** [comment]
Hi @tdeekens, yes, there is a trick but a documented trick. 
We used to set a Script Command as template when it needs to receive extra information to work, i.e: an url address, a token key, no matter what information is needed by the Script Command, it will have `.template` and won't appear in the list.

You can check that information in our [Troubleshooting](https://github.com/raycast/script-commands#troubleshooting) in the README of this repository.
 
Talking specifically about the Script Command you mentioned, in the line [19](https://github.com/raycast/script-commands/blob/master/commands/system/audio-output-switch.template.applescript#L19), you will see a variable waiting to be configured:
```applescript
set asrc to "<Device Name>"
``` 

As this is something documented and answered here, I will close this issue. If you have anything else to add, just comment here or join us to our Community Slack in [https://raycast.com/community](https://raycast.com/community).
