### ISSUE TITLE
Gitlab scripts not working missing python

### ISSUE THREAD

**Issue by weyert** [raycast/script-commands#228]
I am trying out the Gitlab script commands and I have populated `gitconfig.py` with the personal access token and removed `.template` from the files but when select the command in Raycast I am getting:

```
Traceback (most recent call last):
  File "/Users/weyert/Development/Raycast/script-commands/commands/developer-utils/gitlab/gitlab-todos.py", line 36, in <module>
    from gitlabhelper import GitLab
  File "/Users/weyert/Development/Raycast/script-commands/commands/developer-utils/gitlab/gitlabhelper.py", line 4, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'
```

Where do I need to install `certifi`?

**Comment by unnamedd** [comment]
Hi @weyert, 

Did you install the `certifi` in your OS? 

Try this:
```$ pip install certifi```

After that, please, comment here if it worked or not. 😃

**Comment by weyert** [comment]
After a bit of messing around with `pyenv` I was able to get it working :D

**Comment by taobojlen** [comment]
@weyert do you recall what sort of tinkering you had to do with `pyenv` to get it to work? I'm running into a similar issue.

**Comment by lsfiege** [comment]
@weyert can you post the solution please?

**Comment by weyert** [comment]
Sorry can't remember what I did
