### ISSUE TITLE
Table mode

### ISSUE THREAD

**Issue by Rukenshia** [raycast/script-commands#23]
I am running scripts that I currently pretty-print using `column`. This works fine, but looking at other Raycast integrations I think it would be great if you could support outputting via scripts into a table view.
I can imagine printing into stdout in a CSV format, which Raycast then shows as a native table.

**Comment by thomaspaulmann** [comment]
Hey @Rukenshia. We won't add a specific table mode. For richer UI, we will have an [extension API](https://raycast.com/developer-program) that you can use to format things like our root list and add actions. This might include a grid layout at some point but nothing is planned at the moment. 

I'll close this task to keep the issues clean. Please sign up for the developer program to be among the first to use the extensions API.
