### ISSUE TITLE
Search contacts possible?

### ISSUE THREAD

**Issue by RicoTrevisan** [raycast/script-commands#241]
I read the contributing guidelines, but there was nothing about how to request features. Is it OK if I place it here?

I would love to have my contacts searchable from Raycast - much like Spotlight does. Would that be a potential feature in your roadmap?

**Comment by unnamedd** [comment]
Hi @RicoTrevisan,

it is possible to search for your contacts using Raycast, first, you need to activate it in Preferences:
![image](https://user-images.githubusercontent.com/83694/108481587-aa23cb00-7298-11eb-8249-cdc65a309a1c.png)

afterwards, just type `search contacts` and you will see it here:
![image](https://user-images.githubusercontent.com/83694/108481680-c6276c80-7298-11eb-8f29-433e6a22d965.png)

here the list:
![CleanShot 2021-02-19 at 09 57 19](https://user-images.githubusercontent.com/83694/108481853-fa029200-7298-11eb-9d78-907b24087575.png)

as this is not a issue, I will close it and if you need, please just comment on it. 

Feel free to join us in our [Slack community](https://raycast.com/community), will be a pleasure to have you there.
