### ISSUE TITLE
pbpaste output handling and problem with unicode

### ISSUE THREAD

**Issue by japanese-goblinn** [raycast/script-commands#249]
I've faced problem with unicode on [https://ray.so](https://ray.so) that it was not correctly decoded and looks like this.

<img width="827" alt="Screenshot 2021-02-18 at 13 21 31" src="https://user-images.githubusercontent.com/33631005/108342757-3926d980-71ec-11eb-9777-aec396ce855b.png">

So I start digging and find out that for some reason in Raycast script reading from pasteboard with `pbpaste` is not working correctly 

I've modified original `create-image-from-code.sh` to `fullOutput` to print results and what I've got

Examples:

```bash
CODE="кек"
echo $CODE | base64
```

Output: `0LrQtdC6Cg==` // correct

Now same but from `pbpaste` ("кек" is in pasteboard)

```bash
echo $(pbpaste | base64)
```

Output: `Pz8/` // 🧐

<img width="343" alt="Screenshot 2021-02-21 at 20 18 33" src="https://user-images.githubusercontent.com/33631005/108632830-faaa4c80-7481-11eb-9a40-17c41674303c.png">

And final example:

("кек" is in pasteboard)

```bash
echo $(pbpaste)
```

🧐🧐🧐
<img width="862" alt="Screenshot 2021-02-21 at 20 20 21" src="https://user-images.githubusercontent.com/33631005/108632890-3ba26100-7482-11eb-9435-876219fa136c.png">

So I don't really know what a problem here, but I guess that it's something with internal handling of `pbpaste` command output.

**Comment by japanese-goblinn** [comment]
Even more interesting

Input: `привет как дела что делаешь`

```bash
echo $(pbpaste)
```

Output:
<img width="862" alt="Screenshot 2021-02-21 at 20 31 11" src="https://user-images.githubusercontent.com/33631005/108633149-bfa91880-7483-11eb-9503-e68fddf55309.png">

**Comment by japanese-goblinn** [comment]
So we see that for some reason `pbpaste` return content of `developer-utils/`

**Comment by thomaspaulmann** [comment]
That is super confusing... Also, I recently updated the `create-image-from-code` command to properly URL encode the base64 string. Though this might be a different issue.

What's even more confusing is that I get a different result than you when I decode `кек` 🤯 
<img width="326" alt="CleanShot 2021-02-23 at 9 43 52@2x" src="https://user-images.githubusercontent.com/12066405/108912210-3bd86300-7620-11eb-89da-b8fc153f9c6d.png">

**Comment by japanese-goblinn** [comment]
> That is super confusing... Also, I recently updated the `create-image-from-code` command to properly URL encode the base64 string. Though this might be a different issue.
> 
> What's even more confusing is that I get a different result than you when I decode `кек` 🤯
> <img alt="CleanShot 2021-02-23 at 9 43 52@2x" width="326" src="https://user-images.githubusercontent.com/12066405/108912210-3bd86300-7620-11eb-89da-b8fc153f9c6d.png">

Yep, but you're doing this in terminal. Try run this in Raycast script and launch it from app and you'll be surprised 😅

**Comment by thomaspaulmann** [comment]
<img width="862" alt="CleanShot 2021-02-24 at 6 57 45@2x" src="https://user-images.githubusercontent.com/12066405/109051232-35a2bf00-76d2-11eb-8191-e834302e2783.png">

Ok I was able to reproduce this with a simple script command in Raycast:
```bash
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Test
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🤖

# @Documentation:
# @raycast.author Thomas Paul Mann
# @raycast.authorURL https://github.com/thomaspaulmann

echo "Text:"
echo "кек" | base64

echo -e "\n"

echo "Pasteboard:"
echo $(pbpaste | base64)
```

This is rather weird and I don't really have a clue yet what could be the issue.

**Comment by thomaspaulmann** [comment]
Ok, when I put `LANG="ru"` on the top of the script I get something more appropriate.

**Comment by japanese-goblinn** [comment]
> Ok, when I put `LANG="ru"` on the top of the script I get something more appropriate.

Hmm, that's still pretty weird behavior

**Comment by thomaspaulmann** [comment]
I took another pass on this and seems that setting `LANG="en_US.UTF-8"` or equivalents while running the process fixes this issue. I'll push it with the next release and then your scripts hould work properly. @japanese-goblinn it would be great if you can check with next week's update.

**Comment by japanese-goblinn** [comment]
> I took another pass on this and seems that setting `LANG="en_US.UTF-8"` or equivalents while running the process fixes this issue. I'll push it with the next release and then your scripts hould work properly. @japanese-goblinn it would be great if you can check with next week's update.

As I understood from your reply that won't fix the problem, because what this script needs is to dynamically detect language from pasteboard (I use 3 languages very often) to create beautiful text snippet on https://ray.so/

**Comment by thomaspaulmann** [comment]
My fix takes the locale that is currently set in the system. This should also be how the terminal does it and it should cover your case. Most importantly it is to enable UTF-8.
