### ISSUE TITLE
Long running process management like nodemon for local dev

### ISSUE THREAD

**Issue by anonrig** [raycast/script-commands#250]
Is it possible to write a script like `nodemon` or `pm2` to create a better development environment, which tracks running processes, and where logs can be directly accessed via the raycast by search?

**Comment by unnamedd** [comment]
Hi @anonrig, unfortunately at the moment, is not possible implement such extension in Raycast. The Extensions API is in development and you may want to join the [Developer Program](https://raycast.com/developer-program) which will be available somewhen soon.

As I don't think we can't have anything actionable for now, I will close this issue, but if you have any extra comment, please, comment here to let us all know or just reopen the issue.
