### ISSUE TITLE
Brew install not working (?)

### ISSUE THREAD

**Issue by dexterous** [raycast/script-commands#259]
https://github.com/raycast/script-commands/blob/67a9c1b00e230d1f20b568f5d33254344c01f38e/commands/developer-utils/brew/brew-install.sh#L24

Is is just me or does the `brew install` command not work at all?

I suspect the braces around the parameter are the culprit.

**Comment by thomaspaulmann** [comment]
Just tried the script locally and it works for me. Did you tinker around with the brackets?

**Comment by unnamedd** [comment]
I agree those extra brackets are weird there. It's better to remove them.

**Comment by zalewskigrzegorz** [comment]
I also have a problem with brew 
![Screenshot 2021-02-27 at 21 25 21](https://user-images.githubusercontent.com/12560152/109399339-93d5d900-7942-11eb-9e6e-b997cbe50ae6.png)
The brew is already installed on my machine and works in bash, zsh, and fish, What shell raycast use for script commands?

**Comment by unnamedd** [comment]
> I also have a problem with brew
> ![Screenshot 2021-02-27 at 21 25 21](https://user-images.githubusercontent.com/12560152/109399339-93d5d900-7942-11eb-9e6e-b997cbe50ae6.png)
> The brew is already installed on my machine and works in bash, zsh, and fish, What shell raycast use for script commands?

Raycast execute Script Commands in a non-login environment. 
If it can’t find `brew` in your `$PATH` possibly you have it installed in some folder not visible in this kind of environment. 

I have two questions:
- Have you installed brew using their script?
- Are you using a M1 machine?
