### ISSUE TITLE
Add support for running Python 3 scripts

### ISSUE THREAD

**Issue by LarsaSolidor** [raycast/script-commands#260]
Being able to run arbitrary python 3 scripts would _greatly_ enhance the number of things I can automate with Raycast. 

I was thinking you could specify which python 3 binary should be used with a 
`#/path/to/python/`

At the top of the script file

**Comment by thomaspaulmann** [comment]
We already support Python 3. You can find a template [here](https://github.com/raycast/script-commands/blob/d44c8a9b9528ba2a7241fe40aa67783e5464b248/templates/script-command.template.py).
