### ISSUE TITLE
Hope add clipboard automation!

### ISSUE THREAD

**Issue by glink25** [raycast/script-commands#279]
Raycast is so great!
I hope there could be more functions for clipboard history, such as clipboard trigger, which can trigger scripts or shell bash when specified words were mentioned in clipboard, it can possibly enhanced the script ability, and also provide a element method to connect iOS devices and Mac, Thanks! ! !

**Comment by unnamedd** [comment]
Hi @glink25, 
do you have any use of this case you are proposing in mind?

**Comment by nbstoner** [comment]
I have a similar idea. For script commands, most of the time I operate on the contents of the clipboard. Such as translation, search, formatting. I hope the tool can make a preliminary judgment based on the contents on the current clipboard after opening and filter the script command selection. think about the implementation and examples, make a simple judgment of the contents on the clipboard, such as text, media, documents, directories, etc. In the definition of script command, provide metadata definition matching file type. When the content of the clipboard is text, the search, translation and other command items will be displayed in high priority. If it is a file, you can apply the operation steps in the file search.

**Comment by imthath-m** [comment]
Hey @glink25  Thanks for the suggestion. We'll consider this the future.

However, this repo is intended only for sharing script commands with the community. To report issues on Raycast, you can use the `Send Feeedback` command in the app or join [our community in Slack](https://www.raycast.com/community) and reach us directly. 

<img width="290" alt="onboarding-send-screenshot-feedback-dark-2x" src="https://user-images.githubusercontent.com/46041492/111324888-31464200-8691-11eb-8b4d-9ec98d5d516d.png">
