### ISSUE TITLE
custom message for needsConfirmation

### ISSUE THREAD

**Issue by Rukenshia** [raycast/script-commands#281]
I have a script that pulls information from an API - since there is no way of other interactive user input with scripts (and if I understood correctly, script commands will not have such functionality), I was wondering if there was a way to implement a custom confirmation prompt/message option so that the user can confirm a specific action.

For my specific use case:

My script pulls trello cards from a board, and based on the current time selects the closest card. I want to archive this ticket, but would like to confirm that the script picked the correct card.

**Comment by PitNikola** [comment]
Hi, that's interesting use case, thanks for sharing. We are unlikely to provide a way to dynamically change alert text in scripts, but it might be possible in the Typescript API that we're working on right now.
