### ISSUE TITLE
sed regex option (-r or -E) not supported properly

### ISSUE THREAD

**Issue by BoyangMichael** [raycast/script-commands#286]
Hello, I found that the regex option (`-r` or `-E`) of `sed` does not work in the raycast terminal, but normal regexp works. Please check the following screenshots. Any idea what the problem is? Thanks in advance.

FYI, in case this is related to terminal type, the `$TERM` for my terminal is `xterm-256color` and that for the Raycast script is `linux`. 

### `sed -r` in Terminal
```bash
echo "123   456" | sed -r 's/\s+//'
```

![Screen Shot 2021-03-08 at 11 52 55 PM](https://user-images.githubusercontent.com/42609034/110392638-89fe5500-8069-11eb-920b-0eb891db5cab.png)

### `sed -r` in Raycast
```bash
echo "123   456" | sed -r 's/\s+//'
```
![Screen Shot 2021-03-08 at 11 50 06 PM](https://user-images.githubusercontent.com/42609034/110392326-0cd2e000-8069-11eb-953e-e418e2134236.png)

### `sed` with normal regexp in Raycast
```bash
echo "123   456" | sed 's/   //'
```

![Screen Shot 2021-03-08 at 11 52 09 PM](https://user-images.githubusercontent.com/42609034/110392513-54f20280-8069-11eb-84fa-1f9dd14d3c80.png)

**Comment by grzegorzkrukowski** [comment]
Hey @BoyangMichael 

I don't think it's related to Raycast itself - I think it's more `sed`. 
As far as I know the some version of `sed` had problems with `\s`.

Did you try maybe with: `echo "123   456" | sed -E 's/[[:space:]]//g'`  or `echo "123   456" | sed -E 's/[ ]//g` ?

**Comment by BoyangMichael** [comment]
> Hey @BoyangMichael
> 
> I don't think it's related to Raycast itself - I think it's more `sed`.
> As far as I know some versions of `sed` had problems with `\s`.
> 
> Did you try maybe with: `echo "123 456" | sed -E 's/[[:space:]]//g'` or `echo "123 456" | sed -E 's/[ ]//g` ?

Hi @grzegorzkrukowski 

I tried with `[[:space:]]` and `[ ]`. They both work!

You are right. I found that my terminal app and the Raycast do use different versions of `sed`! 

Thanks for the answer and solution!

**Comment by grzegorzkrukowski** [comment]
Ok great it worked !
