### ISSUE TITLE
Installation error on a user account without admin rights

### ISSUE THREAD

**Issue by Garfield-fr** [raycast/script-commands#292]
If you try to update the software with the command "Check update" directly from the software and you have a user account, this is not possible.

Stack trace:
`
Optional(Error Domain=NSCocoaErrorDomain Code=513 "“Raycast” couldn’t be moved because you don’t have permission to access “Applications”." UserInfo={NSSourceFilePathErrorKey=/Applications/Raycast.app, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Applications/Raycast (544).app, NSFilePath=/Applications/Raycast.app, NSUnderlyingError=0x600003ef00f0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
`

**Comment by imthath-m** [comment]
Hey @Garfield-fr, Thanks for reporting the issue. We'll look into it.

However, this repo is intended only for sharing script commands with the community. To report issues on Raycast, you can use the `Send Feeedback` command in the app or join [our community in Slack](https://www.raycast.com/community) and reach us directly. 

<img width="290" alt="onboarding-send-screenshot-feedback-dark-2x" src="https://user-images.githubusercontent.com/46041492/111324888-31464200-8691-11eb-8b4d-9ec98d5d516d.png">
