### ISSUE TITLE
Unable to see my pull requests (or any repositories)

### ISSUE THREAD

**Issue by kahoot-karl** [raycast/script-commands#305]
Hello, I just discovered your product. Works great for jira, thanks a lot!

Reporting a bug or maybe misconfiguration hazard for github. I connected with my account which is part of a private organization. However, I can't see my pull requests or repositories. 

![image](https://user-images.githubusercontent.com/64776986/111142881-767d4d80-8585-11eb-9f09-9edd77cdff04.png)

Happy to help with whatever details you need

**Comment by imthath-m** [comment]
Hey @kahoot-karl, Thanks for reporting the issue.

However, this repo is intended only for sharing script commands with the community. To report issues on Raycast, you can use the `Send Feeedback` command in the app or join [our community in Slack](https://www.raycast.com/community) and reach us directly. 

<img width="290" alt="onboarding-send-screenshot-feedback-dark-2x" src="https://user-images.githubusercontent.com/46041492/111324888-31464200-8691-11eb-8b4d-9ec98d5d516d.png">


As for the issue with GitHub repos and pull requests not showing up, it most likely got to do with the OAuth permissions. You need to provide access for your organizations in your settings [here](https://github.com/settings/connections/applications/32fabff40b685413b5fd). For more info on the GitHub commands in Raycast, please refer [here](https://www.notion.so/raycastapp/GitHub-85ce2eca95c24a699d8c1ae1f962d837).

**Comment by kahoot-karl** [comment]
Thanks for the helpful reply!
