### ISSUE TITLE
[Feature]Add some regular operations on macos

### ISSUE THREAD

**Issue by hzb** [raycast/script-commands#306]
Thanks for providing such a good software, it is recommended to provide some conventional operation commands.

E.g. `empty trash`, `Lock Screen`, `Restart` and more.

**Comment by crstauf** [comment]
@hzb If you browse the code of the repository you posted this issue on, you will see that such commands already exist.

**Comment by hzb** [comment]
@crstauf Sorry for that, I didn't browser the code and habitually executed a few commands like using alfred and didn't find, so I submitted this issue. I will close it.

**Comment by unnamedd** [comment]
Hi @hzb,

please check it out this link here: https://github.com/raycast/script-commands/tree/master/commands

There, you will see what we call “Awesome Script Commands”, it is a README containing all the Script Commands available in this repository, with a nice description provided by the authors and some other informations.

If you have any suggestion, question, report, please join us in our Slack community: https://raycast.com/community
