### ISSUE TITLE
How to disable the default Google Search and DuckDuckGo Search.

### ISSUE THREAD

**Issue by Jax0rz** [raycast/script-commands#309]
the default  Google Search and DuckDuckGo Search can't be disabled.

**Comment by imthath-m** [comment]
Hey @kahoot-karl, Thanks for using Raycast and getting in touch.

However, this repo is intended only for sharing script commands with the community. To report issues on Raycast or send suggestions, you can use the `Send Feeedback` command in the app or join [our community in Slack](https://www.raycast.com/community) and reach us directly. 

<img width="290" alt="onboarding-send-screenshot-feedback-dark-2x" src="https://user-images.githubusercontent.com/46041492/111324888-31464200-8691-11eb-8b4d-9ec98d5d516d.png">

Regarding your question, at the moment there is no option to disable those searches. We'll consider this for the future.
