### ISSUE TITLE
Get an error when trying to build/run this script. (I'm new to this so please inform me of my mistake should there be one!)

### ISSUE THREAD

**Issue by Tech-Aesthetic** [raycast/script-commands#321]
Script editor tells me that it is expecting an "End of Line but is finding a quotation mark" not sure what that means as I copy and pasted directly from GitHub 😅 

I uploaded it to imugur to be more clear.

Thank you for any help!

https://imgur.com/YU02GVk

**Comment by unnamedd** [comment]
@Tech-Aesthetic please, post the code here. The alert is hiding the code, it is impossible to tell you where the problem might be.

**Comment by Tech-Aesthetic** [comment]
Sorry, the code is literally copied and pasted from here 😅 

#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Create To-Do
# @raycast.mode silent

# Optional parameters:
# @raycast.icon images/things.png
# @raycast.packageName Things
# @raycast.argument1 { "type": "text", "placeholder": "Title", "percentEncoded": true }
# @raycast.argument2 { "type": "text", "placeholder": "When (e.g. \"today\")", "percentEncoded": true, "optional": true }

# Documentation:
# @raycast.description Create a new To-Do with title and optional deadline.
# @raycast.author Things
# @raycast.authorURL https://twitter.com/culturedcode/

open "things:///add?title=$1&when=$2"
echo "Created To-Do"

**Comment by Tech-Aesthetic** [comment]
`#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Create To-Do
# @raycast.mode silent

# Optional parameters:
# @raycast.icon images/things.png
# @raycast.packageName Things
# @raycast.argument1 { "type": "text", "placeholder": "Title", "percentEncoded": true }
# @raycast.argument2 { "type": "text", "placeholder": "When (e.g. \"today\")", "percentEncoded": true, "optional": true }

# Documentation:
# @raycast.description Create a new To-Do with title and optional deadline.
# @raycast.author Things
# @raycast.authorURL https://twitter.com/culturedcode/

open "things:///add?title=$1&when=$2"
echo "Created To-Do"`

**Comment by Tech-Aesthetic** [comment]
> @Tech-Aesthetic please, post the code here. The alert is hiding the code, it is impossible to tell you where the problem might be.

We’re you able to get the code working?

**Comment by mattisssa** [comment]
@Tech-Aesthetic works fine for me! Are you sure that you don't have any typos here? I edited your code, try to copy/paste it and run the script again :)

**Comment by Tech-Aesthetic** [comment]
Thank you for looking at it! I copied and pasted, didn't change anything, and I get the same message 😅 Is it possible I need to change a preference or setting of apple script?

https://imgur.com/z59xaiL

**Comment by thomaspaulmann** [comment]
@Tech-Aesthetic I think the issue is that you try to run a bash script as an applescript in the Script Editor. Instead, use the built-in `Create Script Command` with bash as template to create a new script and then insert your script. Then you can execute the script from the Raycast root.

**Comment by grzegorzkrukowski** [comment]
@Tech-Aesthetic did you resolve the problem? From my experience, the default AppleScript editor you are using is breaking files - it's better to use Xcode or Visual Studio Code.
If you still need support, the easiest way will be to reach our community on Slack: https://raycast.com/community
