### ISSUE TITLE
raycast can't open automatically at login

### ISSUE THREAD

**Issue by hzb** [raycast/script-commands#330]
I tried so many times, it can't open automatically at login.

#### Configure

on macOS

![raycast001](https://user-images.githubusercontent.com/535675/112412456-7c2f1c00-8d59-11eb-8ba2-56d425060923.png)

on Raycast

![raycast002](https://user-images.githubusercontent.com/535675/112412508-9406a000-8d59-11eb-92c8-ead5bac763f0.png)

#### How to reproduce

- Configure raycast as above

- Restart your Mac, you will find it.

#### More information

- Raycast version: 1.10.0

- macOS version: macOS Big Sur 11.2.3 (20D91)

**Comment by unnamedd** [comment]
@fe9lix this was fixed two releases ago, right?

**Comment by hzb** [comment]
@unnamedd It was fixed in version 1.11.0 which I updated about 1 hours ago. I think this issue should be closed. 

BTW, the bug still remains in version 1.10.0

**Comment by unnamedd** [comment]
Great! Thanks @hzb!

**Comment by hzb** [comment]
@unnamedd Sorry, I think I need to reopen it, this issue seem to be fixed. I tried on two Macs again, it still remains, only worked once when I upgraded a few days ago.

**Comment by hzb** [comment]
This issue still remains.

**Comment by hzb** [comment]
Seems to be working, closie this issue temporarily.
