### ISSUE TITLE
Ability to add a hidden directory for Script Commands

### ISSUE THREAD

**Issue by dannysteenman** [raycast/script-commands#336]
I noticed it was not possible to add a hidden directory for script commands. That would be a useful feature for people who store their config files stored as dotfiles.

**Comment by thomaspaulmann** [comment]
It is actually possible but you have to drag your hidden directory from the finder into the file picker of Raycast when creating a new script. We'll see if we can show the hidden directories directly, definitely handy for `.raycast` ;-)

**Comment by thomaspaulmann** [comment]
Fixed, gonna be part of the next release :-) Thanks for flagging!

**Comment by varemenos** [comment]
I was just looking for this, trying to set my scripts location to ~/.raycas. I even tried to bypass it with `defaults write com.raycast.macos.plist NSNavLastRootDirectory ~/.raycast` but to no avail.

@thomaspaulmann can you mention the version number that will include this fix?

**Comment by thomaspaulmann** [comment]
Gonna be part of next week’s release. What you can do in the meantime is selecting the .raycast directory in the Finder and drag it to the file picker of Raycast.
