### ISSUE TITLE
Toggle Bluetooth script not working

### ISSUE THREAD

**Issue by crstauf** [raycast/script-commands#341]
The [_Toggle Bluetooth_](https://github.com/raycast/script-commands/blob/master/commands/system/bluetooth.template.applescript) script is not working for me on Big Sur 11.2.3. I have removed `.template` from the filename, and when I run the script I do get the warning about turning Bluetooth off.

Sometimes receive this error:

```
/Users/caleb/Library/Raycast Script Commands/_enabled-commands/bluetooth.applescript:704:705: execution error: System Events got an error: Can’t get window "Control Center" of application process "ControlCenter". (-1728)
```

cc @vincentdoerig @thomaspaulmann

**Comment by vincentdoerig** [comment]
What is your system language? The variable probably needs to be `ControlCentre` if it's British English.

**Comment by crstauf** [comment]
@vincentdoerig Please see screenshot below.

<img width="780" alt="Screen Shot 2021-04-01 at 1 06 31 AM" src="https://user-images.githubusercontent.com/4573033/113246226-918ad580-9286-11eb-86b3-cd0716169323.png">

**Comment by thomaspaulmann** [comment]
Mmh... It's most likely what @vincentdoerig mentioned. Apple likes to change the names of their windows with locales and updates. You can use the `Accessibility Inspector` to figure out names of elements. Seems that there are [some C APIs](https://github.com/search?q=IOBluetoothPreferenceSetControllerPowerState&l=Swift&&type=code) to toggle bluetooth. Maybe we should convert the script command to use this? This seems more reliable.

**Comment by crstauf** [comment]
+1 on C APIs.

**Comment by mattisssa** [comment]
@crstauf has it been solved finally? Or there is still the issue? :)

**Comment by crstauf** [comment]
> has it been solved finally? Or there is still the issue?

@mattisssa As far as I know there's been no changes made, so no reason to think it would work now. Never heard back from @vincentdoerig after posting screenshot of settings.

**Comment by thomaspaulmann** [comment]
We'll handle this natively to make use of the private C APIs and gonna update this issue later. Stay tuned...

**Comment by pcjmfranken** [comment]
Bad bot!  Just a friendly revival bump :)

The script does not work on Catalina in UK English.

Protip (not directly relevant to the issue): The `Bluetooth File Exchange` app asks to enable BT when it's disabled. You can open the app through Raycast, and then hit enter on your external USB keyboard in the dialog so you can use your external trackpad/mouse again without having to open your macbook's lid first.
