### ISSUE TITLE
Brew script doesn't work.

### ISSUE THREAD

**Issue by zalewskigrzegorz** [raycast/script-commands#342]
Whenever I run Brew script, for example, Brew upgrade, I got this error:

`brew command is required (https://brew.sh).`

<img width="523" alt="image" src="https://user-images.githubusercontent.com/12560152/113355612-54cfe480-9341-11eb-840c-519b486a3fa5.png">

Brew works with my shell, and I think Raycast doesn't load the correct $PATCH environment variable.
And I don't see a way how to override it.

**Comment by mattisssa** [comment]
Raycast executes Script Commands in a non-login environment.
If it can’t find brew in your $PATH possibly you have it installed in some folder not visible in this kind of environment.

I have two questions:

Have you installed brew using their script?
Are you using an M1 machine?

**Comment by mattisssa** [comment]
Also, let's ask the creator of brew Script Commands, there are something new issues @unnamedd

**Comment by unnamedd** [comment]
@mattisssa You brought exactly the questions I'd bring related to M1.

@zalewskigrzegorz if you have an M1 machine, brew has a different path for their files which is not part of the folders visible by a non-login, then Raycast will not find it and will show that message.

**Comment by zalewskigrzegorz** [comment]
Oh, sorry, I miss this. Yep, i have an M1 mac

**Comment by unnamedd** [comment]
One of the solutions you will have to apply is: edit the script commands and prepend the whole path for the brew instead of just call `brew`, should be something like: `/opt/homebrew/bin/brew`, this was my way to solve.

**Comment by zalewskigrzegorz** [comment]
This works! Thanks @unnamedd

**Comment by unnamedd** [comment]
@zalewskigrzegorz I’m going to close this issue, if you need anything else, please, let us know just commenting here.
