### ISSUE TITLE
Provide a way to have a preview and also an action for a script

### ISSUE THREAD

**Issue by gizmomogwai** [raycast/script-commands#371]
I have a small program, that i wrap into a script for the raycast scriptcommands, that e.g. looks if i have open pull request and shows them with inline. I would like to be able to press enter there or apple-enter to e.g. open the pull request page.
my command that is wrapped in the script is just a one line call to another script or executable, so one could have something like 

    @raycast.inline command1 arg1 arg2
    command2 arg3 arg4

where command1 would be run for the inline presentation with a poll timer and command2 when enter is pressed.

**Comment by gizmomogwai** [comment]
btw. i love the script commands!

**Comment by imthath-m** [comment]
Thanks for the suggestion. This would be a good addition to Raycast. We'll consider it.

By the way, this repo is intended only for sharing script commands with the community. To share suggestions or report issues on Raycast, you can use the `Send Feeedback` command in the app or join [our community in Slack](https://www.raycast.com/community) and reach us directly. 

<img width="290" alt="onboarding-send-screenshot-feedback-dark-2x" src="https://user-images.githubusercontent.com/46041492/111324888-31464200-8691-11eb-8b4d-9ec98d5d516d.png">
