### ISSUE TITLE
Error when invoking Screen Saver script command

### ISSUE THREAD

**Issue by edmundojr** [raycast/script-commands#386]
Hi! First of all thanks for building Raycast. I’m a long time Alfred user but trying Raycast because that UI is sick! The Linear and Hacker News integration are amazing as well, really liking it!

**The issue:** I’m getting the error below when trying to run the [screen saver command](https://github.com/raycast/script-commands/blob/master/commands/system/screensaver.applescript). Any ideas why? What I’ve tried:

* Change file permissions to 755
* Remove the script completely and add it again

### Error screenshot

![CleanShot 2021-04-30 at 12 56 25@2x](https://user-images.githubusercontent.com/213251/116692011-9771f480-a9b3-11eb-8c3e-7881223b1ad4.png)

Any help appreciated!

**Comment by unnamedd** [comment]
Hi Edmundo, 
the first thing I’d try to do, is to run the Script Command direct in the CLI. To do so, execute this Script Command there and share here with us the result. 

```shell
$ cd ~/Documents/Scripts
$ osascript screensaver.applescript
```
I’m asking you to do this for two reasons: 
- I’d like to see the full message returned by Raycast which was cropped.
- I’d like to see if it’s going to run

To finish my comment here, please, join our community on Slack. There is definitely the best place to report problems and talk directly to Raycast team. Everyone there is very helpful and the community is very active.

Here is the link: https://raycast.com/community

On Slack, my username is @tholanda in case you prefer to discuss directly about this problem.

**Comment by edmundojr** [comment]
Hi @unnamedd! Thanks for getting back so quickly.

Running that script starts the screensaver, no error message is thrown.

BTW, just joined the community :)

**Comment by edmundojr** [comment]
Just figured what was happening.

Raycast needs Automation privileges on Big Sur, more specifically the “System Events” one needs to be enabled.

After checking that box and restarting the app, the Screen Saver command started working again. 

![CleanShot 2021-05-05 at 09 58 10@2x](https://user-images.githubusercontent.com/213251/117118452-af1cf480-ad88-11eb-9bb4-25f56ef3ff4a.png)

I must have dismissed the Window that asks for that option by mistake.

Thanks for the help!
