### ISSUE TITLE
Application crashes when deleting a quick link

### ISSUE THREAD

**Issue by ospfranco** [raycast/script-commands#434]
Simple as that, just create a quick link (any will do), then go to the general settings and extensions, find the quick link, right click and try to delete it, the application will suddenly crash, I already sent the report via apple

**Comment by mattisssa** [comment]
Hey @ospfranco! Yes, there is a bug, thanks for the reporting! 
By the way, we have a Feedback form that you can use to report issues, just type "Feedback" in the main search. 👍 

We will handle the bug. Since it's not relevant to script-commands I'm closing the issue.
