### ISSUE TITLE
[feature-request] install command script like npm install

### ISSUE THREAD

**Issue by JiangWeixian** [raycast/script-commands#436]
thanks for awesome work!, it's able to load command by `npm install -g <command>`, just like alfy for alfred

**Comment by unnamedd** [comment]
Hi, this can be done using Script Commands with Arguments. All the information is available in the README and in the Script Commands already implemented as well. 

Also, I'd like to invite you to two things: 
- Connect to the [slack community](https://raycast.com/community), where your request should be more visible than here.
- Use the Feedback form available in the app to send your feedbacks. Just search for `Send Feedback`
![image](https://user-images.githubusercontent.com/83694/119532545-44f2e080-bd85-11eb-9040-397be11da8b3.png)


As this issue isn't related to any Script Commad, I'm closing it. If you need anything else, please let us know.
