### ISSUE TITLE
Password arguments

### ISSUE THREAD

**Issue by fabn** [raycast/script-commands#437]
I'm trying Raycast and I need to get a password as input for my script, however with current [arguments API](https://github.com/raycast/script-commands/blob/master/documentation/ARGUMENTS.md) there's no way to achieve this and typed password will appear in cleartext on screen.

I think this should be addressed somehow.

Going to be specific I'm doing something like the existing [bitwarden](https://github.com/raycast/script-commands/blob/master/commands/password-managers/bitwarden/unlock.sh#L26) to unlock my 1password vault but I think that you should avoid to publish that kind of scripts until support for hidden password is out.

**Comment by PitNikola** [comment]
Hey @fabn! Thanks for the suggestion. We'll take a look at adding secure input.

**Comment by PitNikola** [comment]
Secure inputs have been added in 1.18.0, thanks for your feedback! Closing the issue.
