### ISSUE TITLE
generate-git-ignore.sh not working

### ISSUE THREAD

**Issue by JiangWeixian** [raycast/script-commands#439]
api in this sh, return error code 1020

**Comment by grzegorzkrukowski** [comment]
Hey @JiangWeixian I just tested the script and it's working fine for me.

What parameters are you passing to the script? 

Also, can you try opening:
https://www.toptal.com/developers/gitignore/api/list

This is the API endpoint the script is using - can you check if it's reachable for you ? 1020 stands for Access Denied - maybe it's not reachable from your location.

**Comment by JiangWeixian** [comment]
@grzegorzkrukowski orz, this website reachable in 4g network🤣. i will check my network. thx.
