### ISSUE TITLE
Feature request. Close PR with comment

### ISSUE THREAD

**Issue by zalewskigrzegorz** [raycast/script-commands#440]
I miss one thing with Github integration sometimes, I need to close PR, but closing without any comment is bad. There is a way to add closing with comment functionality?

**Comment by unnamedd** [comment]
Hi @zalewskigrzegorz, 

you can submit you request using some ways:  

Directly via Feedback form inside of Raycast
<img width="304" alt="image" src="https://user-images.githubusercontent.com/83694/120481507-76386580-c3b0-11eb-899f-bc386e3443df.png">

or joining us in the community on Slack, which is for sure the best place to talk with the Raycast Team: https://raycast.com/community

As this issue isn't related to Script Commands, I'm going to close it. 

Hope to see you there!
