### ISSUE TITLE
This seems to be calculating the time difference wrong

### ISSUE THREAD

**Issue by lewisblackburn** [raycast/script-commands#450]
![image](https://user-images.githubusercontent.com/51877955/120087127-57e71700-c0dd-11eb-853b-aff10198dcaa.png)

**Comment by gumadeiras** [comment]
It's assuming 00:22 is from the same day (which I believe is wrong behavior). Adding `tomorrow` solves it.

![image](https://user-images.githubusercontent.com/5599352/120412667-f2856700-c324-11eb-972c-9c22248a77e1.png)

**Comment by unnamedd** [comment]
Hi Folks,

as this issue isn't related to any Script Command, I'm going to close it and invite you to share your suggestions, bugs or concerns with us in our community: https://raycast.com/communty

Will be a pleasure to have you both there!
