### ISSUE TITLE
Support for chrome-cli

### ISSUE THREAD

**Issue by irealva** [raycast/script-commands#451]
Hi there, I'm trying to figure out how to create a custom script that uses [`chrome-cli`](https://github.com/prasmussen/chrome-cli). For some reason none of the chrome-cli commands work at all although they work perfectly in my own shell environment. This is what I'm trying:

```bash
#!/bin/bash -l

# @raycast.title Chrome CLI
# @raycast.author Irene
# @raycast.description Chrome CLI

# @raycast.mode fullOutput
# @raycast.packageName cli
# @raycast.schemaVersion 1

which chrome-cli # outputs the path correctly

# option 1, produces no output
chrome-cli list tabs

# option 2
CHROMETABS=$(eval chrome-cli list tabs)
echo "$CHROMETABS" # empty variable

#option 3
CHROMETABS2=$(chrome-cli list tabs)
echo "$CHROMETABS2" # empty variable
```

**The output after running on Raycast is:**
<img width="312" alt="empty" src="https://user-images.githubusercontent.com/8978670/120243365-61839280-c235-11eb-9a42-4bb830e7c39f.png">

I ran this through ShellCheck and get no errors. I'm also using a login-shell with `#!/bin/bash -l`

**When I try this command in the Mac terminal it runs correctly:**
<img width="1084" alt="terminal" src="https://user-images.githubusercontent.com/8978670/120243389-6fd1ae80-c235-11eb-95b1-3c26e5048eb5.png">

**Comment by unnamedd** [comment]
Hi @irealva, even though we can help you out here, I’d like to encourage you to join us in our Slack community where we can be more effective and quick solving your problem with you. Here is the url to our Slack: https://raycast.com/community.

**Comment by irealva** [comment]
Solved it by opening up Raycast from my mac Terminal like so:

`/Applications/Raycast.app/Contents/MacOS/Raycast . &`

This grants the right permissions for it to run a script that then runs `chrome-cli`.
