### ISSUE TITLE
Screen saver command

### ISSUE THREAD

**Issue by Luchanso** [raycast/script-commands#452]
Hello, thank you for beautiful instrument, maybe you can add screen saver command, which launch it? 🙂

**Comment by Luchanso** [comment]
I found workaround solution: add bash script with line `/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine`

**Comment by unnamedd** [comment]
Hi @Luchanso, consider to join us on our community on slack and send all the suggestions there and then talk directly to the developers.

As this issues isn't related to Script Commands, I'm going to close it.

Slack Community: https://raycast.com/community
