### ISSUE TITLE
Import/Export configuration

### ISSUE THREAD

**Issue by Luchanso** [raycast/script-commands#453]
Hey, guys, thank you for amazing tools, it would be nice if you add import/export settings, like dotenv files.

I have scripts which installs & configure all my applications on new MacOS, and I want automate raycast installation and config too.

**Comment by unnamedd** [comment]
Hi @Luchanso, 
this is a topic frequently requested by users on Slack and the developers should work on it somewhere in the future. 

I'd like to invite you to join us on our Slack and post your suggestions, questions or just talk there, here's the link: https://raycast.com/community

As this issue isn't related to the development of Script Commands, I'm going to close it. 

Please consider join us on Slack, will be a pleasure to have you there with us.
