### ISSUE TITLE
wallpaper-refresh.applescript not working

### ISSUE THREAD

**Issue by programVeins** [raycast/script-commands#458]
Wallpaper refresh command not working. Check attached video to see how the wallpaper does not change. @crstauf 

https://user-images.githubusercontent.com/25583875/120773720-3b186c80-c53f-11eb-90f7-9747b73102f8.mov

**Comment by crstauf** [comment]
@programVeins Please see [the comment in the script](https://github.com/raycast/script-commands/blob/master/commands/system/wallpaper-refresh.applescript#L6):

> Refresh the wallpaper of the main display's current [Space](https://support.apple.com/guide/mac-help/work-in-multiple-spaces-mh14112/mac).

Does the wallpaper of your first Space change? Also, what are your wallpaper settings? Is the wallpaper randomly selected from a directory of images? If not, then there's nothing to refresh.

**Comment by programVeins** [comment]
@crstauf When you mean 'Refresh the wallpaper of the main display's current Space', I thought you referred to the inconsistency in the wallpapers of spaces in a display and the command will fix them up. Is that not the case? (Like, although two spaces have been changed to a new wallpaper, the current middle space is not updated to match them)

**Comment by crstauf** [comment]
@programVeins Ahh no that's not the scripts use: if your wallpaper is set to randomly select from a directory, the script will prompt the system to select a different wallpaper from the specified directory. I'll adjust the script's description to make that more clear.

**Comment by programVeins** [comment]
Ahh right, my bad then. Will probably take it up and make my own script of what I mentioned! Thank you, closing the issue!
