### ISSUE TITLE
No ability to search within file contents?

### ISSUE THREAD

**Issue by daGUY** [raycast/script-commands#468]
I love using Raycast as a Spotlight replacement, but it seems to be missing one big feature: searching within file contents!

Unless I have something misconfigured, Raycast’s file search feature only seems to search by filename as far as I can tell, and doesn’t actually search within file _contents_ like Spotlight does.

As a workaround, I use Spotlight in the Finder whenever I need to search through file contents, but I’d like to be able to do this from Raycast too.

**Comment by fe9lix** [comment]
Hey @daGUY ! This repository is meant for issues related to script commands only. For general Raycast issues and feedback suggestions, you can join our [Slack community](https://raycast.com/community) or use the feedback feature in the app.
(Btw, file search improvements are coming soon...)
