### ISSUE TITLE
Search Bookmarks as Top Level

### ISSUE THREAD

**Issue by rickroberts** [raycast/script-commands#471]
I don’t know how else to describe this. Can bookmarks be part of the primary search the same way system commands and quicklinks are … without having to invoke _Search Browser Bookmarks_ first? I.e., invoke Raycast, start typing the bookmark name, boom, done.

If this is not the way to request a feature, someone kindly correct me. Thank you all for the excellent work on Raycast.

**Comment by fe9lix** [comment]
Hey @rickroberts ! This repository is meant for issues related to script commands only. For general Raycast issues and feedback suggestions, you can join our [Slack community](https://raycast.com/community) or use the feedback feature in the app.

Regarding your question: You could set up an alias for the bookmarks command via Raycast Preferences and then quickly search and jump into the bookmarks command by typing the alias + SPACE + your search term (e.g., if "b" is your alias, you could type "b somebookmark" in root search to trigger the bookmarks search...)
