### ISSUE TITLE
Clipboard History paste is finicky w/Chrome contenteditable

### ISSUE THREAD

**Issue by jaredpalmer** [raycast/script-commands#474]
As a long time Alfred fanboy, I'm really liking the product so far (been using Raycast for 2-3 weeks). However, I'm finding Raycast's clipboard history pasting to be less stable/functional than Alfred's. It just doesn't seem to be able to paste on every  input/textarea (using Chrome) like Alfred's does. The most annoying for me, is that it doesn't seem to function when composing emails on fastmail.com.

I tried giving Raycast both Accessibility and Input Monitoring permissions in Security & Privacy System Preferences, but still not getting correct paste behavior.

As I started writing this issue, I inspected fastmail's rich text editor, and I am now wondering if this has to do with the fact that it is _not_ an actual textarea element, but rather a div with contenteditable. Meanwhile, Raycast paste works fine in the GitHub textarea I am typing into right now. 

---

MacBook Air (M1, 2020)
macOS Big Sur 11.2.3 (20D91)
Raycast: 1.17.1
Chrome:  91.0.4472.77

**Comment by fe9lix** [comment]
Hey @jaredpalmer ! This repository is meant for issues related to script commands only. For general Raycast issues and feedback suggestions, you can join our [Slack community](https://raycast.com/community) or use the feedback feature in the app.
Would be great if you could repost this via one of those channels.
