### ISSUE TITLE
Where is Raycast config folder? 

### ISSUE THREAD

**Issue by 404cn** [raycast/script-commands#483]
I want to sync config between my company's Mac and home's Mac, but I didn't find there is an config folder?

**Comment by es183923** [comment]
There currently isn't a way to sync config files between computers. You can take a look [here](https://www.notion.so/Migrating-Raycast-Preferences-c574ac993a604819b2dafb97394d06bf) for exporting and importing settings. You should ask questions like these on the [raycast slack community](https://raycast.com/community).
