### ISSUE TITLE
Slack Community

### ISSUE THREAD

**Issue by es183923** [raycast/script-commands#484]
Currently, many people have questions about the app itself and create issues on this repository. It should be made clearer that people should join the slack community to provide feedback for the app. This could happen by adding a link in the README in the first few lines, instead of in the last paragraph.

**Comment by dehesa** [comment]
Hey @es183923, you are right! I will add a couple of lines at the beginning of the `README` file.

Thanks for the input.

**Comment by es183923** [comment]
I feel that we might need to put this in bold as a heading, so that people will actually *read it*. Or, you could add an issue template telling users to join the Slack community for suggestions regarding the app itself.
