### ISSUE TITLE
clipboard history display error when script invoke "pbcopy" command on mac system

### ISSUE THREAD

**Issue by rhettor** [raycast/script-commands#485]
### shell content
```sh
echo "你好" | pbcopy
```

### running on raycast
> displaying "‰Ω†Â•Ω"

it also error when use japanese.

### running on terminal
> displaying "你好"

**Comment by dehesa** [comment]
Hi @rhettor,

Thanks for the feedback, but I am not sure I understand. `pbcopy` just copies stuff to the clipboard. So your example seems to be lacking something. I created a simple `compact` script copying `你好` with `pbcopy` and then pasting it for display with `pbpaste` and it does the right thing.

**Comment by rhettor** [comment]
System: Mac 11.4 (Default language: zh)
Raycast Version: 1.18.0

![bug](https://user-images.githubusercontent.com/8852109/123061065-df564a80-d43d-11eb-94c8-e9257e0308c7.gif)

**Comment by dehesa** [comment]
Hey @rhettor,

Sorry for the delay. I can replicate the bug. Thank you for the feedback. I will pass it along.

**Comment by nhojb** [comment]
Hi @rhettor, we're investigating a fix for this issue in Raycast.

However, in the meantime, if you change the script `LANG` environment, `pbcopy` should then work as expected e.g.
```
export LANG=en_US.UTF-8
echo "你好" | pbcopy
```

**Comment by rhettor** [comment]
@nhojb It's work. 

My `LANG` env is default empty in bash shell, but running raycast script, it echo "en_CN.UTF-8", where is from? Could fork default shell env?
