### ISSUE TITLE
Add possibility to display firstLine of fullOutput inline

### ISSUE THREAD

**Issue by MattisBrizard** [raycast/script-commands#488]
Hi ✋, 

First of all thanks for this tool, just discovered it yesterday and find it really useful.

By playing with script-commands I found that it would be nice to be able to display the first line of fullOutput mode like in inline mode (as a way to quick see the main information and have more precision by opening fullOutput).
Could be by an optional parameters that we could set to true.

Mattis

**Comment by nhojb** [comment]
Hi @MattisBrizard, thanks for the feedback.

We are currently working on a full extensions API which will allow more customisation of output. Watch this space.
