### ISSUE TITLE
Please have option to non-expiry of clipboard history

### ISSUE THREAD

**Issue by overfullstack** [raycast/script-commands#492]
I am a developer and I use clipboard history extensively to store a lot of things temporarily like addresses, terminal cmds, directory paths etc.
Alfred stores clipboard history for 3 months max. But Raycast only supports 30 days max. Please increase this limit or if possible, have an option to never expire it.

**Comment by nhojb** [comment]
Hi @overfullstack, thanks for the feedback. I've added this to our issue tracker.

Note that in future it's best to send feedback from Raycast itself, or via our Slack community (https://raycastcommunity.slack.com/). This issue tracker is for script commands only.
