### ISSUE TITLE
Raycast window is behind iTerm's Hotkey fullscreen terminal

### ISSUE THREAD

**Issue by tpucci** [raycast/script-commands#496]
Hello Raycast,

I am not sure if the issue is in the right place.

Raycast's Spotlight window is behind iTerm's Hotkey fullscreen terminal.

See it in the following video :

https://user-images.githubusercontent.com/16262904/124559737-51666080-de3c-11eb-8ead-bf59e5fa3f47.mp4

**Comment by es183923** [comment]
> 🚨 For anything that is not related to script commands, please [send us an email](feedback@raycast.com), use the feedback command within Raycast, or join the [Slack community](https://www.raycast.com/community).

[README.md](https://github.com/raycast/script-commands/blob/master/README.md)

Please read the README before creating any issues.

**Comment by unnamedd** [comment]
Hi @tpucci, as mentioned by @es183923, this issue isn't related to Script Commands itself, so I'd kindly ask you to use the Feedback form inside of Raycast to report a bug or use our Slack community.

That being said, I'm closing this issue. If you have anything else, please, let us know.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/83694/124629110-6a453500-de81-11eb-928e-b3d6499813a4.png">
