### ISSUE TITLE
JIRA search issue command doesn't wildcard search JIRA ticket number

### ISSUE THREAD

**Issue by samleemc** [raycast/script-commands#505]
Hi there,

One of my favourite function is the JIRA search embedded in Raycast, however, I am very disappointed that the JIRA Search function doesn't cover wildcard JIRA Issue number. I believe in a normal dev team, people communicated using JIRA number without the prefix (for example, DEV-1024, people will just use "1024"), and having the ability to search the issue by providing just the number is great.

**Comment by unnamedd** [comment]
Hi @samleemc,

please, consider to submit this report directly via Raycast using the Send Feedback form. 
![image](https://user-images.githubusercontent.com/83694/125251958-24142980-e2f8-11eb-823f-2fd5341e7ae6.png)

You can also connect to the team directly using our Slack community, here: https://raycast.com/community

As this issue isn't related to Script Commands, I'm closing it.
If you need anything else, related to Script Commands, this is the repository for it.

**Comment by samleemc** [comment]
thanks! submitted
