### ISSUE TITLE
[Feature Request] Hotkey recording support with double tap

### ISSUE THREAD

**Issue by chen86860** [raycast/script-commands#506]
I want defined hotkey to  double tap`control` key, but raycast not yet support current. Please consider add this feature in the next publish.

**Comment by unnamedd** [comment]
Hi @chen86860,

I'd like to kindly ask you to use the Send Feedback form inside of Raycast to request features, report bugs and/or send a message to the team.  
![image](https://user-images.githubusercontent.com/83694/125251545-bb2cb180-e2f7-11eb-90fd-f41428e77eb7.png)

We have an open community on Slack where you also can request, report and just talk. Here's the link: https://raycast.com/community.

As this issues isn't related to Script Commands itself, I'm closing this issue.
If you need anything else, please let us know.
