### ISSUE TITLE
CPU usage is huge on mousemove

### ISSUE THREAD

**Issue by theRenard** [raycast/script-commands#507]
On Activity Monitor I can see a huge cpu consumption when moving mouse

![raycast consumption](https://user-images.githubusercontent.com/61255863/125453545-e20c1304-e762-4bc1-9966-9f077ddab730.png)

**Comment by unnamedd** [comment]
Hi @theRenard,

I'd like to kindly ask you to report this directly via Send Feedback form from inside of Raycast or if you think this is a bug, you can also submit it in our community on Slack. This channel is not a proper way to report bugs which are not related to Script Commands.

Inside of Raycast you can type feedback, you will see as a result "Send Feedback" like in the following screenshot:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/83694/125486347-44e33304-73ce-489a-89f5-0e329d71e11a.png">

Also, if you prefer, access our community on https://raycast.com/community

As this issue isn't related to the Script Commands, I will close it. 
Let us know if you need anything else.

**Comment by theRenard** [comment]
Sorry, I'll do as asked :)
