### ISSUE TITLE
Inline output mode and refreshTime

### ISSUE THREAD

**Issue by Jed-Z** [raycast/script-commands#513]
Is `refreshTime` field required when the mode is "inline"? Otherwise it seems to fall back to "compact" mode.

Scripts in `developer-utils/ip` have inline mode but `refreshTime` is missing. I found a related PR #42, and a [commit](https://github.com/raycast/script-commands/commit/e6db628866d139753f9f0b67a7c3d0d6b314d102#diff-0c873f95ac42cbac70473f5e784180767def799411cf3346ee8bd02c7c097cda) in which `refreshTime` was removed.

**Comment by es183923** [comment]
`refreshTime` isn't required. The scripts in `developer-utils/ip` copied your IP to your clipboard, and since that refreshed once an hour, it updated your clipboard too. That was not what it was supposed to do, so I removed the `refreshTime` part.

**Comment by Jed-Z** [comment]
Thanks for your reply. It is reasonable not to let it update the clipboard automatically every once in a while.
But, without `refreshTime`, the mode turns into "compact" by itself instead of "inline". Is it the expected behaviour?

```bash
# @raycast.mode inline
# @raycast.refreshTime 1h
```
![image](https://user-images.githubusercontent.com/32293986/125874982-c4a58df2-65ab-4e33-bfc1-58fbed40a32c.png)

```bash
# @raycast.mode inline
```

![image](https://user-images.githubusercontent.com/32293986/125875037-8c3549ed-2e06-4102-9ba3-cc4406dcc932.png)

**Comment by es183923** [comment]
I'm sorry, it seems like `refreshTime` is required after all. (I don't work for Raycast nor am I affiliated with it)

You can take a look at the "Create Script Command" and see that if you select `inline`, an option for "Refresh Time" appears.

**Comment by PitNikola** [comment]
It is indeed required. I've updated [this page](https://github.com/raycast/script-commands/blob/master/documentation/OUTPUTMODES.md) to mention it explicitly.
