### ISSUE TITLE
[Bitwarden] Option to choose a result for multiple results

### ISSUE THREAD

**Issue by guga4ka** [raycast/script-commands#524]
Currently, Bitwarden command for vault search just shows a plain JSON, is it possible to parse it and show human-readable results? Also, it would be nice to add a link to log-in  page and populate username/password fields

**Comment by unnamedd** [comment]
copying the master minds of Bitwarden in the thread: @PSalant726 @jaklan

**Comment by jaklan** [comment]
@guga4ka currently the command returns pretty-printed JSON, not the plain one - how would you imagine more "human-readable" output?

<img width="862" alt="Screenshot 2021-07-27 at 15 55 28" src="https://user-images.githubusercontent.com/24907857/127167626-f819c64f-f432-4c5d-9252-829aea75e24e.png">
And as you can see, links are already there if you added them as URIs in Bitwarden - if you click any of them, they will open in your default browser. If you have Bitwarden extension installed in the browser, credentials should be automatically filled in (ofc if the vault is unlocked in the extension) and personally I find it as the most secure solution, with no need to recreate a behaviour of Bitwarden extensions, but maybe @PSalant726 has a different idea.

**Comment by PSalant726** [comment]
@jaklan  You've got some courage posting the output of that command in a public thread 😅

@guga4ka Can you provide an example of what you mean by "human readable"? How would you prefer the output to look?

I could see the command doing some further processing on the JSON to achieve an output like:

```
Result 1:
  Title:    {{ entry name }}
  Username: {{ user name }}
  Password: {{ password }} (optional)
  URLs:     {{ list of URLs }}

Result 2:
  ...
```

I cannot see this command doing much else though, and FWIW I have begun work on an integration with the Raycast API. I expect the new package to have a much better all-around user experience.

**Comment by guga4ka** [comment]
@PSalant726 the out is a just prettified JSON, basically, I'm looking for the same experience as alfred and 1password have. But as I understand it isn't possible to achieve with script-command. My current output is 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/13866979/127174500-c9c82062-66ef-4a43-9fff-08cfd61e845b.png">

So it might be useful to print results as text, and maybe add "copy to clipboard" link for password(not sure if pbcopy can handle kind of `pbcopy://` links). Also is it possible to navigate through results without a mouse?

**Comment by PSalant726** [comment]
> it might be useful to print results as formated text without JSON array/objects

This seems achievable by adding some formatting logic to the current script. I would encourage you to open a PR if you'd like to see these changes; it would likely be a long time before I would have a chance to work on it myself, as I am currently prioritizing an implementation with the API alpha in my very limited free time.

> add "copy to clipboard" link for password

This doesn't seem possible based on the current limitations of script commands, and is why I implemented the [_Copy First Matching Password_ script](https://github.com/raycast/script-commands/tree/master/commands/password-managers/bitwarden#copy-first-matching-password). I realize it's not a perfect solution, but it was the best I could do based on the available features of the Bitwarden CLI and Raycast script commands. You're welcome to brainstorm other options and open a PR 😄 .

> is it possible to navigate through results without a mouse

You should be able to scroll the search results using the arrow keys.

**Comment by guga4ka** [comment]
@PSalant726 thx for your answers. I'm going to close issue and think if i can improve current script. Basically find first matched password is fitting me for 99% of cases.
