### ISSUE TITLE
Enable File Search in root

### ISSUE THREAD

**Issue by rmvdesign** [raycast/script-commands#552]
I'd love to be able to search on Raycast like Spotlight or Alfred, but I don't like that I have to enter File Search mode to do it. Is there any way to add an extension's list elements to root, so Root shows everything it normally does and also the entries from the module you specified as "Enabled in Root" or something similar?

**Comment by unnamedd** [comment]
Hello @rmvdesign,

this repository is specific for Script Commands related issues. Your request doesn’t fit in this repository, for that reason, I’d like to ask you to report your in two different ways:
1 - Open Raycast and search for “Send Feedback”, will you see a form where you can submit complaints, suggestions, compliments and so on, or
2 - Join us in the Slack Community at https://raycast.com/community and post your message in the #suggestion channel.

As this issue isn’t related to the Script Commands, I’m going to close it. If you have any further question, please, let me know.
