### ISSUE TITLE
Clipboard history is slow to load and search

### ISSUE THREAD

**Issue by a-marionette** [raycast/script-commands#555]
v1.21.1

Clipboard is very slow to load (2-4s) and search. Retention for 30 days.

**Comment by unnamedd** [comment]
Hi @a-marionette,

please use this repository to report any problem related to Script Commands.

To report bugs, compliments, suggestions or any other stuff, please use our Slack Community at raycast.com/community or use the Send Feedback form inside of Raycast (just open Raycast and type Send Feedback).

As this issue isn’t related to this repository, I’m closing it! Feel free to comment here in case you have further questions.
