### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by DreiAugenFrosch** [raycast/script-commands#558]
When I create a script via "Extensions" > "Scripts" > "Create script command" and choose "NodeJS" as template, I get the following error message when I run the script: "env: node: No such file or directory".

I have NodeJS installed on the system via NVM and when I run the script directly from the terminal, everything works fine. But I can't get it to launch in Raycast.

Thats the (default) script:

```
#!/usr/bin/env node

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title test
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 🤖

console.log("Hello World!");
```

**Comment by unnamedd** [comment]
First question I need to bring here @DreiAugenFrosch: is your Node installed globally?

Raycast runs in a non-login environment, if node is only installed for your user, Raycast won’t be able to find it and then you will receive the message “No such file or directory”.

A test you can do is changing your shebang to make Raycast run in login environment.

Follow the instructions in our [Troubleshooting and Faqs](https://github.com/raycast/script-commands#troubleshooting-and-faqs).

**Comment by unnamedd** [comment]
As this issue didn't get any interaction from the original author, I'm closing it to keep clean our list of issues.

**Comment by svenjacobs** [comment]
I have the same issue. I use [Volta](https://github.com/volta-cli/volta) to manage multiple Node versions. The `node` executable is placed in `$HOME/.volta/bin`. Currently I have to add the following shebang to my scripts

```
#!/usr/bin/env PATH=$PATH:/Users/sven.jacobs/.volta/bin node
```

which however doesn't make my scripts very portable because of the hardcoded path. What other options are there?

**Comment by axhamre** [comment]
@unnamedd Would you mind giving an example how to run the script as login-shell with Node.js?
