### ISSUE TITLE
Script commands don't show up on Macbook M1

### ISSUE THREAD

**Issue by maneeshsethi** [raycast/script-commands#579]
Hi great app!

I've downloaded script commands here and added the directory. That didn't work. I also created a sample script command in the watched directory, and it doesn't show up ever in Raycast. I can run the script from terminal, but it never shows in raycast. 

Any ideas?

Images for examples

![image](https://user-images.githubusercontent.com/620799/132838373-d7760257-e0c6-4473-ad25-f7a040f11235.png)
![image](https://user-images.githubusercontent.com/620799/132838393-28123647-100b-4722-ab09-acbaed56f0b1.png)

**Comment by dehesa** [comment]
Hi @maneeshsethi,

Sorry for the delay on answering this. Are you still having the issue? In any case, for support problems on how to use Raycast, please head to the [Slack channel](https://www.raycast.com/community), it is easier to debug any problem there.
