### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Angelk90** [raycast/script-commands#592]
Hi, would it be nice if this project were possible to have several support languages?

**Comment by dehesa** [comment]
Language support is something we want to tackle for this repo, the app, and the API we are working on. However, that requires a non-trivial amount of work to provide a satisfactory service and I am currently unable to tell you when that will be.

We are a very international team in Raycast and we are the first ones that would enjoy it (at the very least to show our families in a language they can understand) 😄
