### ISSUE TITLE
Uninstall procedure and preference settings

### ISSUE THREAD

**Issue by Angelk90** [raycast/script-commands#593]
Hi, congratulations for the fantastic project.

I noticed one particular thing, the following:

1) I installed the application via dmg, downloading it from the site
2) I started the application
3) I was asked to enable or disable some things, that is, to set preferences
4) I have tested app
5) So far so good, so I tried to uninstall apps to test.
6) I went to the lanchpad and tried to uninstall it via the command option (⌥) since the application is not installed via the Appstore, it seems that the command does not work.
7) So to uninstall it I went to the application finder and I deleted the application, putting it in the trash.
8) I tried to install the application again through the dmg, downloaded previously.
9) I was no longer asked to set preferences, step (3)

How come these happen?
Shouldn't preference settings be removed?

**Comment by dehesa** [comment]
Hey @Angelk90,

Glad to hear you are enjoying Raycast. Regarding your questions:
- Launchpad will only show the `x` for applications downloaded in the App Store as you have rightly guessed.
- Moving Raycast from `/Applications` to the trash only deletes the application code and assets, not any preferences you may have set during the usage of the app.

This is common to any mac app (not only Raycast). The preferences are saved in different places, but they usually can be found in the hidden folder `~/Library/Application Support` followed by the name of the app or the reverse DNS of the app. Check it out, you will probably see a lot of data from apps you have previously uninstalled.

This have lead to the creation of "professional uninstaller" apps such as the free [AppCleaner](https://freemacsoft.net/appcleaner) or the paid [CleanMyMac](https://cleanmymac.macpaw.com).

@Angelk90, for further questions regarding Raycast, please use the [Slack community](https://www.raycast.com/community) or [send us an email](feedback@raycast.com). We try to keep this repository as focus as possible in scripts only.

**Comment by Angelk90** [comment]
@dehesa : It would be useful then to insert in the menu or in the settings, something like this:

1) Which allows you to delete application preferences
2) It allows you to uninstall application, then simply delete Raycast from / Applications it is brought to the trash
wondering if you want to delete application preferences as well

Other:
When the application is installed if it already finds previous preferences it should ask you if you want the old settings or new ones.

**Comment by dehesa** [comment]
Hey @Angelk90, thanks for your thoughtful write up. I will pass it along, but this is not the place to discuss feature request. I will encourage you to bring this conversation up in the #suggestions slack channel or via email.
