### ISSUE TITLE
Force keyboard locale

### ISSUE THREAD

**Issue by whitehander** [raycast/script-commands#594]
Hi, Raycast is very good to alternative solution from Alfred.
Alfred has Force Keyboard option for using other keyboard language users.
Sometimes keyboard locale set other languages, change locale procedure is inconvenience
Because most script command is english.

It is possible to add options like that?

![Screenshot 2021-09-29 09 12 05](https://user-images.githubusercontent.com/4279615/135181957-47991d1d-3138-4f42-965c-11e33e83dc7a.png)

**Comment by dehesa** [comment]
Hi @whitehander,

I believe this is what you mean:
![CleanShot 2021-09-29 at 07 49 26](https://user-images.githubusercontent.com/684318/135210631-d209d698-9279-4724-b1b9-7bc2082b5240.png)

@whitehander for further questions regarding Raycast, please use the [Slack community](https://www.raycast.com/community) or [send us an email](feedback@raycast.com). We try to keep this repository as focus as possible in scripts only. Also, you will probably get much quicker replies in the slack community than here.

**Comment by whitehander** [comment]
@dehesa Oh, sorry I can't see that option!!
I will close this issue. Thank you for your answer.

**Comment by youtextme** [comment]
Agree Raycast is a strong Alfred alternative for many — Force Keyboard / locale is a fair parity gap.

Workaround some switchers use: macOS Input Sources hotkey + a small Raycast Script Command to flip layout, while Alfred keeps Cmd-Space only for locale-forced flows until an API option exists.

https://www.raycast.com/?via=girish
Affiliate — commission if you upgrade to Pro. Free Raycast is enough to evaluate the rest of the switch.
