### ISSUE TITLE
Clipboard History stopped working

### ISSUE THREAD

**Issue by FezVrasta** [raycast/script-commands#595]
Hi, it's been a couple of days since the clipboard history stopped working, if I copy some text it's not stored in there.

I checked the macOS permissions and I see Raycast in the accessibility section.

**Comment by dehesa** [comment]
Hey @FezVrasta,

Thanks for contacting us about your problems; however this repo is exclusively related to scripts (as stated at the top of the README). To get a solution to your problem or any question you might have about Raycast, please join the [Slack community](https://www.raycast.com/community) (where you would get the fastest response), or [send us an email](feedback@raycast.com), or use the feedback command within Raycast.
