### ISSUE TITLE
[Feature Request] Fuzzy search thought

### ISSUE THREAD

**Issue by im-AMS** [raycast/script-commands#596]
Is this a feature in your timeline?

What exactly I mean

**Current behaviour**

I want to search for `Create Script Command`. In current behaviour I need to type the whole thing or use arrow keys to reach the command.

**Suggested behaviour**

I should be able to filter out by typing `crscr` which is the first few characters of `Create Script Command`.

**Comment by dehesa** [comment]
Hi @im-AMS,

We'd like to keep this repo as focus on script commands as possible (i.e. creation and modification of scripts by the community). For suggestions or inquiries in Raycast roadmap, please checkout the [#suggestion slack channel](https://www.raycast.com/community) (we are very responsive there). Alternatively, you can [send us an email](feedback@raycast.com), or use the feedback command within Raycast.
