### ISSUE TITLE
Create a topic/tag for github

### ISSUE THREAD

**Issue by panckreous** [raycast/script-commands#612]
Searching gh for "raycast" isnt as bad as searching the internet for just "Swift" buuut why not grow the ecosystem here, too. People who have public raycast scripts can then tag theirs as well so we can see everything in one place, star the topic etc, then someone will create awesome-raycastwhatever and get a bunch of love, oh the places we could go. 

It'll be like https://github.com/search?o=desc&q=raycast but for you! For us!* 

ex: 
https://github.com/topics/raycastapp

*I hope my use of exclamation marks added to everyone's excitement while reading this

**Comment by es183923** [comment]
First, lease post such suggestions in the [Slack community](https://www.raycast.com/community). Second, all scripts should be PRed into this repository, and extensions in [the extensions repo](https://github.com/raycast/extensions).
