### ISSUE TITLE
Compact mode doesn't bring out output toast when triggered by global shortcuts

### ISSUE THREAD

**Issue by shenghan97** [raycast/script-commands#627]
Hello!!

I was trying to create a script where raycast can give me feedback after the script is done. However, when I set the output mode to Compact, the output won't show up at all on my screen when it was trigger globally with a shortcut (without opening raycast's main window first). It will work fine when the output mode is silent or full output and a minimal toast notification or raycast's main window will show up correspondingly. 

Could this be a bug? Or is this what it was intended? 

Thanks!!!

**Comment by imthath-m** [comment]
@shenghan97 Thanks for bringing this up. 

We have identified the issue and will work on a fix. In the meantime, you can use `silent mode` to see the output when Raycast is closed.

**Comment by imthath-m** [comment]
Hey @shenghan97, this is fixed now in 1.27.0. 

If you run a script command which has `compact` mode using a global shortcut, the Raycast window will come to the front and you will see the toast at the bottom. If you do not want the Raycast window to come to the front, use `silent` mode.
