### ISSUE TITLE
Allow adding Packages as Script Directories

### ISSUE THREAD

**Issue by samdze** [raycast/script-commands#631]
I was trying to create e Swift Playground to use it as a Script Command, but PlaygroundName.playground can't be selected as a valid directory inside Raycast preferences.

**Comment by dehesa** [comment]
Hey @samdze ,

Sorry it took us so long to answer this. My apologies. Regarding your issue, indeed a `.playground` file cannot be selected as a script directory; only regular folders are currently supported.

I can understand why you would wanted that and I am adding that issue to the backlog, but in all honesty I don't think we will have time to enable such functionality soon. Sorry.

**Comment by unnamedd** [comment]
hey @samdze, may I ask why you need a Swift Playground to run as a Script Command? A single Swift file isn't enough for you?

**Comment by samdze** [comment]
Thanks!
@unnamedd my main reason was that Xcode could enable auto-complete in Playground projects, but not in isolated Swift files.

**Comment by unnamedd** [comment]
Unless all your structs and class are inside of the same file, the auto completion will work really well, but if you have multiple files, then you start to have a problem. One of the Script Commands in Swift I wrote was in just one file (the Swift part) and using Xcode with auto completion.

Just to let you know: it is composed by two files. You can check it here:
- [Shell file](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/search-script-command.sh)
- [Swift File](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/search-script-command.swift)

If you have any question regarding that, please let me know. Will be a pleasure to help you on that subject.
