### ISSUE TITLE
Error UNABLE_TO_GET_ISSUER_CERT_LOCALLY inside a snippet

### ISSUE THREAD

**Issue by Kikobeats** [raycast/script-commands#632]
Hello,

I'm trying to create a script command that is essentially pipe-ing a CLI command. This is my code snippet:

```
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Microlink API
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon https://cdn.microlink.io/logo/apple-touch-icon-60x60.png
# @raycast.argument1 { "type": "text", "placeholder": "url", "optional": false }

# Documentation:
# @raycast.description Microlink API integration
# @raycast.author Kiko Beats

microlink "$1"
```

Under the hood, it's using [@microlink/cli](https://github.com/microlinkhq/cli) global npm package.

Well, the thing is, when I perform the command using my terminal, all is fine:

![CleanShot 2021-12-11 at 20 37 47@2x](https://user-images.githubusercontent.com/2096101/145689408-e0d7ccdc-ed51-4173-877a-c2d8b8976509.png)

However, doing the same using the Raycast command throws an error:

![CleanShot 2021-12-11 at 20 38 19@2x](https://user-images.githubusercontent.com/2096101/145689427-988b31a0-d686-4586-bc50-f1bbb106b171.png)

After adding some logs, [this](https://stackoverflow.com/a/31862256) is what is happening, and effectively if I add a `rejectUnauthorized: false` to the internal HTTP request done by the library it works; However, I prefer to don't do that.

How is the Raycast context for executing this kind of snippets? how it possible the error is just occurring in Raycast? 🤔

**Comment by dehesa** [comment]
Hey @Kikobeats,

Sorry it took us so long to answer this. My apologies. Regarding your issue, I don't have knowledge of how `microlink/cli` works, but it seems it is probably related to scripts running in a non-login shell as explained in the [README's FAQs](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#bash-profiles-and-environmental-variables) and the [CONTRIBUTING.md](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#bash-profiles-and-environmental-variables). Could that be the case?

**Comment by Kikobeats** [comment]
Thanks for the reply!

Looks like it was something related to my system. It's working like a charm.

Would you accept a PR adding it? 🙂

**Comment by dehesa** [comment]
Please do, we always like new contributions!

**Comment by Kikobeats** [comment]
done at https://github.com/raycast/script-commands/pull/643 🎉
