### ISSUE TITLE
Executing `zip` in bash in compact mode does not work

### ISSUE THREAD

**Issue by antonreshetov** [raycast/script-commands#635]
In `fullOuput` mode, however, everything works correctly. 

```bash
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Test
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🚀
# @raycast.argument1 { "type": "text", "placeholder": "Date (YYYY-MM-DD)" }

DATE=$1
REPO_NAME="some_name"

checkout_and_zip () {
  cd /path/to/$REPO_NAME
  COMMIT=$(git log --until="$DATE" --pretty=oneline | awk '{print $1}' | head -n 1)
  git checkout $COMMIT
  cd ..
  zip -r $1 $1 -x "$1/node_modules/*"
  cd $1
  git checkout master
}

checkout_and_zip $REPO_NAME
```

**Comment by dehesa** [comment]
Hi @antonreshetov,

Sorry it took so long to answer this. I have been able to replicate and there seems to be indeed an issue. I will investigate further and I will try to land a fix soon.

**Comment by dehesa** [comment]
Ok, the issue is related to your usage of the `zip` command in pair with the `compact` mode. Compact mode expects a single answer or an error, but `zip` prints out a lot of stuff about what it is doing along the time it takes to zip. It works in `fullOutput` mode, because Raycast doesn't have such expectations.

To make it work, you need to add the `-q` flag to your zip command. Such as:
```bash
zip -q -r $1 $1 -x "$1/node_modules/*"
```

**Comment by antonreshetov** [comment]
Thanks for the clarification, but it is not obvious and even more so not described in the documentation.

**Comment by dehesa** [comment]
It is true that it is not clear (I will write it down in the documentation). To be completely honest, at the beginning I thought it was a bug in Raycast, but it is related to how the Foundation's `Process` is set up to work. The set up is different for `fullOutput` and `compact` modes.

Hopefully, it makes sense now. Don't hesitate to ask anything else.
