### ISSUE TITLE
[Feature request] Vim keybindings?

### ISSUE THREAD

**Issue by Anthonyive** [raycast/script-commands#636]
I'm new to this app. I didn't find vim-related extensions in the store and settings in the preferences. I wish I could use J/K to go up and down.

**Comment by unnamedd** [comment]
Hello, 

For feature request, you should use one of the two following ways:
First, `Send Feedback` form from inside of Raycast
or
second, using our Slack community at: [raycast.com/community](https://raycast.com/community).

<img width="862" alt="image" src="https://user-images.githubusercontent.com/83694/146679964-6eb46a03-00f8-494d-80b8-27f09acf9711.png">

As this request isn't related to Script Commands, I'm going to close it. If you have any further question, please comment here and me or someone else will reply you as soon as possible.
