### ISSUE TITLE
Configure Raycast itself via CLI

### ISSUE THREAD

**Issue by AlexeyRaga** [raycast/script-commands#638]
Is it possible to configure Raycast itself via CLI or config files? 
It'd be helpful for setting up Raycast automatically for new machines (enable launch by default, set the hotkey, etc.)

**Comment by unnamedd** [comment]
Unfortunately not. What it is possible is export your preferences and import again on your new machine, but those steps are done via Raycast Preferences, not via CLI.

As this issues isn't related to Script Commands, I'm going to close it. If you have any further question, please comment in this thread or use our Slack community: raycast.com/community.
