### ISSUE TITLE
Execute node and brew commands from non root macOS

### ISSUE THREAD

**Issue by MassivDash** [raycast/script-commands#639]
Hello

Is there anyway to specify the custom paths for non root / custom installation of brew with nvm.
Node seems to be not present during the execution, here is a example error from the BitWarden 

```
usr/bin/env: node: No such file or directory
```
I tried specifying the path in the settings directly to nvm node version bitwarden cli bin and to brew bitwarden path

for manage brew extension i tried specifing the custom bre path and got 

```
Error: Command failed with EACCES: /Users/fakeUser/homebrew/bin services list
spawn /Users/fakeUser/homebrew/bin EACCES

spawn /Users/fakeUser/homebrew/bin EACCES
__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
Process.ChildProcess._handle.onexit:child_process:282:19
onErrorNT:child_process:477:16
processTicksAndRejections:task_queues:83:21
``

**Comment by pcjmfranken** [comment]
The `EACCESS` error indicates a permission problem, but I'm not sure if your Node even works without first sourcing NVM (which it isn't by default in the non-login shell Raycast uses to execute these scripts).

You could create a new Bash Raycast script in which you manually `source /path/to/nvm.sh` and then execute the script from a different file with `node /path/to/script.js`.

**Comment by zbysir** [comment]
Use `whereis node` to find node location, then relace the first line of script.js to `#!/usr/bin/env /Users/bysir/.nvm/versions/node/v16.20.2/bin/node
`
