### ISSUE TITLE
Global hotkeys

### ISSUE THREAD

**Issue by rtyshyk** [raycast/script-commands#646]
Hi there,

Is it possible to add global hotkey to the custom script? Means it must be possilble to run Script without opening RayCast, like Window Management or Clipboard manager works.

**Comment by unnamedd** [comment]
Yes, just access Raycast Preferences > Extensions and you will see Hotkeys. Everything there can have a shortcut for quick access.

As this issue isn't related to Script Commands itself, I'm closing this issue.

If you have any further question related to Raycast, the best way is using our community: raycast.com/community
