### ISSUE TITLE
Composing commands/saving predefined parameters

### ISSUE THREAD

**Issue by essential-randomness** [raycast/script-commands#657]
Hi,
Is there a way to create a new command by using an existing command with predefined parameters? For example, I'd like to create a "run [project] storybook" command that leverages the [run shell command in iterm](https://github.com/raycast/script-commands/tree/master/commands/apps/iterm) command to open a predefined folder and run `yarn run storybook` in it.

I would expect this to be possible either with this script-command interface or from raycast itself, but I don't understand how. If this is somewhere in the documentation, I couldn't find it.

**Comment by dehesa** [comment]
Hi @essential-randomness,

Sadly Raycast doesn't offer such functionality at the moment. We are looking into "workflows"; i.e. to be able to trigger commands (whether script commands, applications, quicklinks, etc.) in order, but I can't give you any ETA on that.

To overcome your current situation, you will need to create your own script or TS extension.

**Comment by pcjmfranken** [comment]
You can run that applescript with the argument from any other script. Just put the following in a new Raycast Bash script (Raycast meta comments removed for brevity):

```bash
ITERMSCRIPT="/full/path/to/iterm-run-shell-command.applescript"
PROJECT="/full/path/to/project"

osascript "$ITERMSCRIPT" "cd \"$PROJECT\" && yarn run storybook"
```

Alternatively, if you have multiple projects, feel spent/tired (or just lazy, not judging), and have a high tolerance for nasty things:

```bash
ITERMSCRIPT="/full/path/to/iterm-run-shell-command.applescript"

PROJECTS=(
  "/path/to/first/project"
  "/path/to/second/project"
)

printf -v OSASCRIPT_OPTS '"%s",' "${PROJECTS[@]}"

TARGET_PROJECT="$(osascript -e "return choose from list {${OSASCRIPT_OPTS%,}}")"

osascript "$ITERMSCRIPT" "cd \"$TARGET_PROJECT\" && yarn run storybook"
```

Same as before, but with a native MacOS select dialog to pick a project.

The `printf` transforms array `$PROJECTS` into string literal `"/path/to/first/project","/path/to/second/project",` saved to `$OSASCRIPT_OPTS`. That dangling comma would angry Applescript so it's removed with this `${joined_and_quoted%,}`.

For cleaner project selection definitely create that custom Raycast extension. That workflow concept @dehesa mentioned would be perfect for this.

**Comment by dehesa** [comment]
Thanks for the detailed input @pcjmfranken 👏

@essential-randomness I will close this issue for now, because there isn't anything else we can do. Fell free to reopen it or open a new issue if you need something else.
