### ISSUE TITLE
system/audio/airpodsbattery.sh: doesn't work with AirPods 3rd generation

### ISSUE THREAD

**Issue by hossammourad** [raycast/script-commands#659]
As the titles says, when I run the command it says that no AirPods are connected, but they were.

**Comment by unnamedd** [comment]
cc @itsnwa

**Comment by dehesa** [comment]
I believe this is @qeude baby.

**Comment by unnamedd** [comment]
Oh damn, you are right @dehesa, @qeude is the original developer! 
Thanks for correct my mistake! :D

**Comment by unnamedd** [comment]
As @qeude doesn't seem to be around to help to fix the bug, I'd like to invite someone from the community to help to fix it. 

What about you, @hossammourad? Do you think you can on that?

**Comment by hossammourad** [comment]
> As @qeude doesn't seem to be around to help to fix the bug, I'd like to invite someone from the community to help to fix it.
> 
> What about you, @hossammourad? Do you think you can on that?

Sure. I will give it a shot this week.

**Comment by hossammourad** [comment]
Here is the fix PR https://github.com/raycast/script-commands/pull/678

**Comment by dehesa** [comment]
You are the real MVP!
