### ISSUE TITLE
How to run script with 'sudo' command?

### ISSUE THREAD

**Issue by qiyuan-wang** [raycast/script-commands#664]
Hello,

I want to write a sh script for restarting bluetooth, like 'sudo pkill bluetoothd', but it would run failed with password issue.

I  find [flush-dns.sh](https://github.com/raycast/script-commands/blob/master/commands/system/flush-dns.sh) script in commands folder, which runs with sudo, too.
Is there any way to run script with 'sudo'?

**Comment by qiyuan-wang** [comment]
Solved it with argument feature and `sudo -S`

**Comment by poxin13** [comment]
Having this issue with the mentioned flush-dns.sh script. It runs but doesn't actually clear the cache likely due to sudo.

I modified the script as:
```
sudo -S dscacheutil -flushcache
sudo -S killall -HUP mDNSResponder
```
 
This did not fix the issue either. Running the commands in terminal directly works fine, and prompts for sudo password.

**Comment by poxin13** [comment]
This worked for me:

```
password="yourpassword"

echo "$password" | sudo -S -k dscacheutil -flushcache
echo "$password" | sudo -S -k killall -HUP mDNSResponder

echo -e "\nDNS cache flushed"
```
