### ISSUE TITLE
DeepL App translate script command does not pass through query to DeepL App (Raycast Mac)

### ISSUE THREAD

**Issue by replete** [raycast/script-commands#673]
## Environment
* MacOS Monterey 12.2
* Intel Macbook Pro 13 2020 2.0ghz
* Raycast Mac 1.27.1
* DeepL 3.1.33440

# Repro:
1) Install Raycast
2) Clone this repository
3) Add `deepl` directory to Script Commands Extensions Item in Raycast app preferences window
![Screen Shot 2022-02-05 at 11 01 43](https://user-images.githubusercontent.com/812139/152639361-57de9aa9-ef01-40bd-b116-9fc7d18a3d87.png)
4) Trigger 'Deepl App Translate' via Raycast with text 'du hast'  ![Screen Shot 2022-02-05 at 11 09 12](https://user-images.githubusercontent.com/812139/152639629-0f175031-8b3b-4b0e-a671-a86f8fc80b8c.png)
5) DeepL window activates without populating text query ![Screen Shot 2022-02-05 at 11 10 18](https://user-images.githubusercontent.com/812139/152639704-f46b6d51-20bf-48de-a8dc-8be3b0c4e315.png) 

Apologies if this is not the correct place for these issues.

**Comment by replete** [comment]
@jonohewitt I see this script was written by you. Any ideas?

**Comment by jonohewitt** [comment]
I can confirm it's not working for me anymore either. This script uses a bit of a hacky method of accessing the text fields via the GUI so it can break when DeepL update their app structure. I'll try to write a fix and send in a PR.

**Comment by replete** [comment]
@jonohewitt Awesome! This is what's great about Raycast, fixing stuff in Alfred was much more involved.

Having a main repo to collect the best scripts under `raycast` is a great idea, because most people using this are doing similar things.

Cheers

**Comment by jonohewitt** [comment]
Yeah I love the collaboration within the Raycast community too! 

I've just uploaded the fix above - please could you give it a go by replacing your current `deepl-app-translate.applescript` file with [the update here](https://github.com/raycast/script-commands/blob/8a6de38fd7f5db17bf88acf6e7d67e9ba9c1f674/commands/apps/deepl/deepl-app-translate.applescript) and let me know if it works?

**Comment by replete** [comment]
![Screen Shot 2022-02-05 at 14 48 56](https://user-images.githubusercontent.com/812139/152646721-bb022ffe-c1f5-412d-9ee0-33f4183d285f.png)

@jonohewitt Works great, thanks for fixing it.

btw I just wrote a few commands for Obsidian, if you use it:
https://github.com/replete/raycast-script-commands

**Comment by jonohewitt** [comment]
Great! Yeah the auto-detect often isn't the best with one or two word inputs but it gets a lot better with longer phrases.

Oh cool good luck with the commands - I don't use Obsidian personally but have been meaning to give it a try!
