### ISSUE TITLE
Argument defaults

### ISSUE THREAD

**Issue by chrisrowe** [raycast/script-commands#686]
I'd love to be able to specify the default argument for scripts

**Comment by chrisrowe** [comment]
![](http://up.chri.sr/Screen-Shot-2022-02-18-10-15-35.53-1645179342.png)
![](http://up.chri.sr/Screen-Shot-2022-02-18-10-15-54.98-1645179356.png)

**Comment by dehesa** [comment]
Hey @chrisrowe,
Thanks for writing your idea/feature request here. This would indeed be useful, but it has some design ramifications that we need to think about. Such as letting the user still see the placeholder text but communicating that in case of not inputing any text, the value would be xx. I don't think just pre-filing the default value is useful.

In any case, I appreciate your input and I have written your request. However I cannot make any promises when and if it will be implemented. In the mean time, you can just write the default value in code 😄
