### ISSUE TITLE
command not found	nil

### ISSUE THREAD

**Issue by HemalR** [raycast/script-commands#695]
Hi,

Thanks in advance for an awesome tool!

I'm trying to create a bash script shortcut to Raycast but am facing an error (likely a user error based on misunderstanding something on my part):

`vercel: command not found	nil`

The command works fine on my terminal. Is there something basic I am doing wrong/overlooking? I've tried googling around but I think I am searching for the wrong things.

Thanks for any help/guidance.

**Comment by clnhs** [comment]
If you're using nvm to manage your Node JS versions, then whichever packages you installed won't be available to the script as Raycast doesn't run in your login shell.

Exporting the `~/.nvm/node/version.number/bin` path at the beginning of a test script allows me to use the vercel command just fine.

e.g.

```
#!/bin/bash
export PATH="~/.nvm/versions/node/v17.4.0/bin/:$PATH"

vercel #command works
```

**Comment by HemalR** [comment]
@clnhs solution did the trick, thanks! 👍
