### ISSUE TITLE
Raycast / Endel Scripts: stop or pause

### ISSUE THREAD

**Issue by mauzon** [raycast/script-commands#717]
Is there any way (or script) to pause or stop Endel's playback?

**Comment by dehesa** [comment]
There is a bunch of Endel scripts [here](https://github.com/raycast/script-commands/tree/cec906b393682cd43759d09e7b1dd3c72f22213c/commands/media/endel). I have no idea what Endel is, but maybe what you look for is there.

**Comment by mauzon** [comment]
Thanks @dehesa, I reviewed it already. All of them are about starting some soundscape to play. I was looking a way to pause or stop its playback, perhaps Endel.io's dev can advise.

**Comment by dehesa** [comment]
The script developer is @huangsemao, maybe he can tell us how we can do this. You piqued my curiosity @mauzon, so I went and downloaded the app and I am giving it a try. I would be curious how Sergey was able to discover the URL scheme options.

**Comment by huangsemao** [comment]
Hi guys, 

1. I asked Endel's support - do they have any URL-Scheme or CLI to change soundscape or volume?

They told me their URL-Scheme

> Our developers are telling me that we have an internal scheme for these purposes. For example, you can start a soundscape using it like this [https://endel.io?type=playing_mode&value=focus](https://endel.io/?type=playing_mode&value=focus). Unfortunately, there are no controls for audio volume in the spec. They are also warning that this scheme is subject to change and they can't guarantee that it will work in the future

2. Then just using logic and this example I found more commands:

URL: endel://?type=playing_mode&value=mode
Modes: study, recovery, relax, focus, sleep, plastikman, alanwatts, grimes

URL: endel://?type=scenario&value=scenario&duration=1200
Scenarios: sports, working, meditation, unwind, studies, powerNap, selfCare, reading, yoga

URL: endel://?type=alarm
URL: endel://?type=timer

*3. For such investigation, you could also search strings in the app binary using Hex Editor(e.g. Hopper Disassembler). BUT this method may be illegal, so I won't recommend it

**Comment by dehesa** [comment]
Great, thanks for the thorough explanation, @huangsemao. If I continue using the app after some weeks, I may build a Raycast extension for it listing the scenarios and letting you choose duration, etc. That would require contacting Endel support again, but they seem to be helpful. Also, any of you may want to pursue that, @huangsemao or @mauzon 😆

**Comment by mauzon** [comment]
Awesome! Thanks a lot @dehesa! 
I've built [PomoDone App](https://pomodoneapp.com/) integration (macOS version) using Bash > URL scheme to start my favourite soundscape for my timers, but when my countdown timer is over (or stopped manually, o paused) I'd love to use the best way to stop the playback rather than just exit the Endel (my current workaround).

**Comment by dehesa** [comment]
That makes sense, but doesn't the play/pause media key works for Endel too? I understand you would like something very specific for Endel, but it is a good work around. You may want to contact Endel support directly @mauzon (same as Sergey did).

**Comment by huangsemao** [comment]
@mauzon @dehesa as I understand Endel doesn't have play/stop/pause/resume command

I think the fastest way to pause/resume Endel install this shortcut(https://www.icloud.com/iclouddrive/067KPYE8-GplLNjv1f-e7Dviw#Endel) and run it by url-scheme shortcuts://run-shortcut?name=endel

**Comment by mauzon** [comment]
@huangsemao Thanks a lot for the advice and the workaround. This shortcut works with active playback (e.g. YouTube or Spotify) but switching focus to the Endel app solved the problem: 

```
do shell script "open /Applications/Endel.app"
do shell script "open shortcuts://run-shortcut?name=endel"
```
