### ISSUE TITLE
Problem with Calculate 

### ISSUE THREAD

**Issue by duypham9895** [raycast/script-commands#725]
132864+149024+281833+-157947+122090+-1+122090+-1+503625+-503625+353525+-353525+543125+-543125+266625+-266625+123886+-123886+194538+-194538+92430+-92430+1846625+-1846625+765115+-765115+353525+-353525+503625+-503625+554980+-554980+1374600+-1374600+2

Link gg calculate: https://www.google.com/search?q=132864%2B149024%2B281833%2B-157947%2B122090%2B-1%2B122090%2B-1%2B503625%2B-503625%2B353525%2B-353525%2B543125%2B-543125%2B266625%2B-266625%2B123886%2B-123886%2B194538%2B-194538%2B92430%2B-92430%2B1846625%2B-1846625%2B765115%2B-765115%2B353525%2B-353525%2B503625%2B-503625%2B554980%2B-554980%2B1374600%2B-1374600%2B2&rlz=1C5CHFA_enVN972VN972&oq=132864%2B149024%2B281833%2B-157947%2B122090%2B-1%2B122090%2B-1%2B503625%2B-503625%2B353525%2B-353525%2B543125%2B-543125%2B266625%2B-266625%2B123886%2B-123886%2B194538%2B-194538%2B92430%2B-92430%2B1846625%2B-1846625%2B765115%2B-765115%2B353525%2B-353525%2B503625%2B-503625%2B554980%2B-554980%2B1374600%2B-1374600%2B2&aqs=chrome..69i57.556j0j1&sourceid=chrome&ie=UTF-8

![Screen Shot 2022-05-16 at 17 08 21](https://user-images.githubusercontent.com/37096506/168570092-938e122f-8e11-46eb-92b3-314da08e0fe6.png)
2

![Screen Shot 2022-05-16 at 17 10 10](https://user-images.githubusercontent.com/37096506/168570429-e3e8de17-346a-47bd-9502-7295a468863f.png)

**Comment by dehesa** [comment]
Hey @duypham9895 ,

Thank you for taking the time to file a bug; however this is not related to script commands. As you can see at the beginning of the [repo's README](https://github.com/raycast/script-commands#readme):

> 🚨 For anything that is not related to script commands, please [send us an email](feedback@raycast.com), use the feedback command within Raycast, or join the [Slack community](https://www.raycast.com/community).

Please use any of such channels for feedback.
