### ISSUE TITLE
Possible to increase padding to costum size

### ISSUE THREAD

**Issue by DaveBouman** [raycast/script-commands#738]

**Comment by dehesa** [comment]
Hi @DaveBouman,

What do you mean by this? Could you please add some more details? Maybe even a screenshot.

Please keep in mind what we state at the top of the [README file](https://github.com/raycast/script-commands#readme). This repo manages issues and PRs related to script commands. For anything else Raycast related, please [send us an email](mailto:feedback@raycast.com), use the feedback command within Raycast, or join the [Slack community](https://www.raycast.com/community).

**Comment by unnamedd** [comment]
Due to lack of better description, I'm closing this issue. Please, if you have any further comment @DaveBouman, please let us know.
