### ISSUE TITLE
sh script output removes line breaks

### ISSUE THREAD

**Issue by Mattyy94** [raycast/script-commands#742]
Hi, I've created a sh script to run a jrnl command. When I run this command in the terminal I will see the output with line breaks, for each day which is nice.

But when I run the same command using Raycast sh script the output will remove the line breaks and output the result in a single line. Is there a way to change this behavior? 

e.g. 
expected output

```
2022-06-27 10:06 started with us-278

2022-06-28 09:15 finnished with us-278

2022-06-28 09:30 started with uf-62

2022-06-28 13:56 finnished with uf-62

2022-06-28 15:49 started with uf-73 
```

real output: 

```
2022-06-27 10:06 started with us-278 2022-06-28 09:15 finnished with us-278 2022-06-28 09:30 started with uf-62 2022-06-28 13:56 finnished with uf-62 2022-06-28 15:49 started with uf-7
```

**Comment by dehesa** [comment]
Hey @Mattyy94.

I am terribly sorry this took so long. The past weeks have been a bit crazy in Raycast HQ. I just tried to replicate your behavior but everything seems to be working for me. Could you paste your script or something simulating the issue? Maybe also a screengrab.

**Comment by dehesa** [comment]
I will close this issue since we haven't heard from @Mattyy94 for a while, but I am happy to reopen if we get more information.

**Comment by Mattyy94** [comment]
@dehesa  I'm so sorry for not replying. See below my script and a screengrab attached:

I've made an little script for JRNL from - to command, but maybe my script has a wrong setting?

```
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Journal from - to
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🖊️
# @raycast.argument1 { "type": "text", "placeholder": "From" }
# @raycast.argument2 { "type": "text", "placeholder": "To" }
# @raycast.packageName jrnl.from-to

# Documentation:
# @raycast.description Get the Journal entries from - to
# @raycast.author Matthijs


echo `/usr/local/bin/jrnl -from "$1" -to "$2"` 
```
screengrap of output
<img width="736" alt="image" src="https://user-images.githubusercontent.com/8201391/183837226-4724cf03-fd41-4e89-9bf6-dad165cdb425.png">
