### ISSUE TITLE
Script run in background

### ISSUE THREAD

**Issue by ARui-TW** [raycast/script-commands#749]
Hi, I'm trying to run a script in the background. For example:
```shell
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title timer_v3
# @raycast.mode compact

# Optional parameters:
# @raycast.icon ⏳
# @raycast.argument1 { "type": "text", "placeholder": "minute", "optional": false }
# @raycast.argument2 { "type": "text", "placeholder": "title", "optional": true, "percentEncoded": true }

setalarm() {
    sleep $(echo "$1 * 60" | bc)
    osascript -e 'display notification "'"$1 minute timer complete!"'" with title "'$2'" sound name "Glass"'
}

setalarm $1 $2 &
```
But Raycast will still show it is "Running script..."
Is there any possible way to solve it?
Thanks!

**Comment by landendanyluk** [comment]
you can use `@raycast.mode silent` in the script parameters

**Comment by landendanyluk** [comment]
set `@raycast.mode` to `silent` and remove the `&` at the end of your last line, which is blocking the shell from exiting (and Raycast from returning control).

**Comment by ARui-TW** [comment]
It works just as I wanted! Thank you for your reply!
