### ISSUE TITLE
Availability script ignores calendar end time if calendar entries with earlier end time intersect

### ISSUE THREAD

**Issue by philffm** [raycast/script-commands#750]
Hola raycast community,
https://github.com/raycast/script-commands/blob/4f1727eaa3e90c02fa711a61a736797a57b18848/commands/system/copy-availability.swift
<img width="173" alt="Screenshot 2022-08-05 at 13 49 23" src="https://user-images.githubusercontent.com/6079545/183071545-b54c08b0-f889-4099-acff-10188fff4d56.png">

The given schedule results in the following output:
"Here's my availability for today:
- 09:00 - 09:00
- 13:00 - 16:30"

Will check, whether I can fix the script by myself and propose a PR but maybe someone instantly has an idea how to fix it.

Cheers, Phil

**Comment by dehesa** [comment]
Hey @philffm,

I have fixed the script for you and also expanded its functionality. You can find it [here](https://github.com/raycast/script-commands/blob/master/commands/system/copy-availability.swift). Let me know if it works for you 😉

**Comment by philffm** [comment]
Works like charm - amazing! Thanks a lot & enjoy the Berlin sun today 🙌
