### ISSUE TITLE
Add Elixirlang support.

### ISSUE THREAD

**Issue by SangKD** [raycast/script-commands#753]
Thank you for this wonderful [tool](https://ray.so/).

Could you please add support for [Elixir](https://elixir-lang.org/)?

**Comment by unnamedd** [comment]
If you have Elixir running on your machine, then Raycast will work for you. The support for the programming languages are not inside of Raycast, but in the user's machine.

As this issue does not relate to any Script Command topic, I'm gonna close it. In any case, you can join our community: raycast.com/community
