### ISSUE TITLE
macOS Ventura Script Run Error

### ISSUE THREAD

**Issue by hasimyerlikaya** [raycast/script-commands#754]
I'm using macOS Ventura Version 13.0 Beta (22A5321d)
I can not run scripts. The error message is below.
How can I fix that?

Error: Process tried to run, but failed

![image](https://user-images.githubusercontent.com/7986394/183642325-0c3c7d71-4827-4b6f-bc27-0975ec88c507.png)

**Comment by hasimyerlikaya** [comment]
Although I use simple scripts, none of them work.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/7986394/184129030-16452220-9500-4318-aa2d-3973a1990b9c.png">

**Comment by nhojb** [comment]
I've also checked that scripts are running on Ventura beta `22A5321d` and everything seems to be working as expected.

Couple of things you could try:
1. Reboot your Mac 😄 
2. If this doesn't resolve the issue, please post your console logs. There are instructions for how to enable logging [here](https://www.notion.so/raycastapp/Getting-logs-via-Console-app-d56af04333a148a6a9e4ca5971f81898)

**Comment by hasimyerlikaya** [comment]
@nhojb Thank you.

This is error message.

"exec of /Users/hasimyerlikaya/Raycast/Scripts/google-gmail.sh denied since it was quarantined by Telegram and created without user consent, qtn-flags was 0x00000086"

**Comment by nhojb** [comment]
So the macOS has set the quarantine flag on your script because it was downloaded and is considered "untrusted" by the system. You should be able to remove the flag like this. It should work as expected afterwards.

```
xattr -d com.apple.quarantine <path to>/google-gmail.sh
```

**Comment by hasimyerlikaya** [comment]
@nhojb Thank you, That fixed my problem.
