### ISSUE TITLE
Hue - Error: env: zx: No such file or directory

### ISSUE THREAD

**Issue by dimitribocquet** [raycast/script-commands#756]
I am a freshly user of Raycast, and I am trying to use the Hue script commands.

I have installed only one for now: https://github.com/raycast/script-commands/blob/master/commands/home/philips-hue/hue-rooms-inline.template.mjs

I have installed `zx` and set my Hue Bridge IP address and my username (created via [meethue.com](https://developers.meethue.com/develop/get-started-2/)).

When I try to run the script, I have this error:

![CleanShot 2022-08-13 at 10 22 54](https://user-images.githubusercontent.com/3192298/184475680-7f7dd5f2-be45-4274-99fc-432135db234a.png)

I can run `zx` in my terminal.

Could you please tell me if I missed something?

Thank you!

**Comment by dehesa** [comment]
This sound like #558. Please, check it out and let me know.
