### ISSUE TITLE
Unable to install create-image-from-code extension

### ISSUE THREAD

**Issue by Rin-Akaia-eth** [raycast/script-commands#766]
Raycast version: 1.39.2

```
Reason: Could not install extension from development sources
Domain: commands
Time: 03:52:54.485
Underlying: 
	Reason: The given URL is not a directory
	Domain: commands
	Time: 03:52:54.485
```

**Comment by dehesa** [comment]
Hi @Rin-Akaia-eth 

I am not sure I am understanding your problem, but it seems like you are trying to install a "script" as a Raycast "extension". Scripts and extensions are different things:
- A script is a single file with self-executable functionality (i.e. an AppleScript, a JavaScript file, or a bash script). They get _recognized_ by Raycast here:

  ![CleanShot 2022-09-05 at 13 13 00](https://user-images.githubusercontent.com/684318/188436157-d3349317-eebc-49cc-b91b-82367dd5ac2e.png)

- A Raycast extensions is a package/folder of typescript/javascript functionality that get installed in the Raycast store or through the import extension command.

<img width="684" alt="CleanShot 2022-09-05 at 13 15 54" src="https://user-images.githubusercontent.com/684318/188436548-308c085b-a9d6-4232-b171-73c2c914c513.png">

Anything in [this repo](https://github.com/raycast/script-commands) is a script. Anything in the [Raycast extensions](https://github.com/raycast/extensions repo) is an extension.

**Comment by Rin-Akaia-eth** [comment]
Oh, I see it now, I thought extensions _are_ the scripts. Thanks!
