### ISSUE TITLE
Issues running scripts

### ISSUE THREAD

**Issue by kikujiro-mms** [raycast/script-commands#769]
I have an AppleScript in a designated script directory. It is properly recognised and available in Raycast. I can open the script directly in Script Editor and it works fine. It used to work fine when triggered from Raycast, but without my changing it at all I am now getting an error per the below screenshot.

Restarting doesn't help. No idea how to troubleshoot this.

<img width="302" alt="Screenshot 2022-09-08 at 18 08 57" src="https://user-images.githubusercontent.com/4154334/189183549-ed7c0875-f498-4f21-a2e8-5aae52708481.png">

**Comment by dehesa** [comment]
Hi @kikujiro-mms,

This is a common problem with AppleScripts and it is related to the encoding used when you created/modified the script. Raycast tries to solve it, but it seems it can do better (we are working on it).

## Solution
1. Open your AppleScript (it will usually open in the legacy AppleScript Editor).
2. Copy the whole text content of the script (⌘+A, to select all, ⌘+C to copy the text).
3. Remove the AppleScript file.
4. Create a new file with a newish code editor (VSCode, TextEdit, etc.).
5. Copy the script text content (⌘+V) and save the file.
6. Execute in Raycast as usual.

## Issue Explanation
Most text out there is encoded with UTF-8; however the AppleScript Editor uses a legacy encoding which has problems with some non-latin languages and newer ways of inputing text (such as emoji). All the scripts in this repo are UTF-8 and if you just download them, the would work as expected. But as soon as you open one AppleScript with the AppleScript Editor, make some changes, and save that script; the encoding will be changed. That is why I recommend to make changes with a newer Editor (usually VSCode).

**Comment by remusris** [comment]
I had the same issue and this was a life saver.  Thanks for the tip.
