### ISSUE TITLE
Is there a way to stop the scripts? Celebrate Script runs unitll the process is done!

### ISSUE THREAD

**Issue by afrid18** [raycast/script-commands#772]
I have celebrate script configures, when I try to run it with the paraments as 100 & 1 sec, it seems that there is no way to stop the process, except to kill the Raycast app itself. 
Is there any work around?

<img width="842" alt="image" src="https://user-images.githubusercontent.com/59523682/190254832-c9342ec7-63ab-4210-b698-dec533e60709.png">

**Comment by dehesa** [comment]
Hey there @afrid18,

There is indeed currently no way to stop a "silent" script. I made the mistake to run the script you were indicating with the same parameters 😆

This hasn't been an issue so far, but I can definitely see how this is beneficial. I will write the request down in our ticket service, but I don't make any promises of when and if the feature will be implemented.
