### ISSUE TITLE
Add a default script-commands directory

### ISSUE THREAD

**Issue by pomdtr** [raycast/script-commands#775]
I think that raycast should add a default script commands folder (`~/.config/raycast/scripts` ?)

It would allow application developper to put script commands in the config dir when they want to extend raycast, without needing to create a dedicated extension.

It would also benefit the [store extension](https://www.raycast.com/tholanda/script-commands) from @unnamedd, since the command dir would become an optional pref :slightly_smiling_face:

**Comment by pomdtr** [comment]
There is some security issues to consider, so maybe a confirm alert would be necessary.

**Comment by dehesa** [comment]
Hey @pomdtr, thank you for the feedback. It has indeed some pros and cons. The current main worry is auto-executing inline scripts. We are discussing internally and we might introduce it to Raycast, but I don't make any promises.

In any case, thank you for bringing this forward!
