### ISSUE TITLE
Python operation clipboard to write Chinese garbled characters

### ISSUE THREAD

**Issue by yuemingming** [raycast/script-commands#777]
Raycast version:1.37.1

## Steps To Reproduce
Code ：
``` python
#!/usr/bin/env python3

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title TestColipard
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖

# Documentation:
# @raycast.author sakura
import subprocess


def set_clipboard_data(input_data):
    p = subprocess.Popen(['pbcopy'], stdin=subprocess.PIPE)
    p.stdin.write(input_data)
    p.stdin.close()
    p.communicate()


resultStr = u'中文测试'
data = bytes(resultStr, 'utf8')
set_clipboard_data(data)
```

## The current behavior
When I run this script with RayCost I get garbled characters
## The expected behavior
normal Chinese display

**Comment by dehesa** [comment]
Hi @yuemingming,

Thank you for taking the time to send this bug and I apologize this took so long to get reviewed. I have been able to replicate and confirm the bug. I will tackle it and hopefully fix it in the following two releases.

**Comment by Jhakir** [comment]
I'm not able to reproduce this issue on my Mac. I'm getting the expected output:

SCRIPT:
<img width="580" alt="Screen Shot 2022-09-30 at 11 06 12 PM" src="https://user-images.githubusercontent.com/5099176/193384099-dcfecc91-ec59-4b10-a45c-59f13c5824e7.png">

Value from clipboard generated by script:
<img width="775" alt="Screen Shot 2022-09-30 at 11 07 10 PM" src="https://user-images.githubusercontent.com/5099176/193384226-38b2f965-c9e2-4a57-894e-a52cbb655dd4.png">

I'm on a Mac OS version 12.4
