### ISSUE TITLE
Mic on off toggle script error

### ISSUE THREAD

**Issue by RazorII** [raycast/script-commands#778]
When I run the [mic toggle script](https://github.com/raycast/script-commands/blob/master/commands/system/audio/toggle-mic.applescript) I get the following error:
![image](https://user-images.githubusercontent.com/1577315/192096506-f759d124-e724-44e1-bd31-f6463c0a0697.png)

I am able to run the script manually when I open it, just not through Raycast.

**Comment by dehesa** [comment]
Could this be related to #769 ? Would you mind checking it out?

**Comment by RazorII** [comment]
Yup, just saving it to a copy of the template.sh file and renaming it without ever opening it works.

Thank you for your help!
