### ISSUE TITLE
Issue with new scripts adding an emoji, causing script to fail

### ISSUE THREAD

**Issue by iamdannywyatt** [raycast/script-commands#786]
I'm by no means an expert when it comes to scripting, AppleScript, etc, but I noticed that when I create a new script using Raycast, it automatically adds the robot emoji. When I then try to run the script, it fails. Once I removed that line, the script ran without issues.

![image](https://user-images.githubusercontent.com/96640778/199824644-23efd4a8-919a-41a5-88a1-0fa98fdf9331.png)

**Comment by iamdannywyatt** [comment]
Hi @dehesa 

Thank you so much for the detailed reply.
Yes, I tried creating 3 scripts:
1 - Never opened it with either Script Editor or VS Code: worked
2 - Made small changes inside Script Editor and saved it: _**stopped working**_
3 - Made small changes inside VS Code and saved it: worked

I don't know if this is relevant or not, but I also noticed that if I grab the code from a brand new script created with the extension, open Script Editor, paste it and save it, the icon is different from the one created and saved using the extension. 

![image](https://user-images.githubusercontent.com/96640778/200577777-a03838f0-91e0-45df-add3-c9e95f330bae.png)

The one on top is the one created and saved using the extension, the bottom one is created and saved using the Script Editor, so even though they are both AppleScript files, macOS is seeing them as different, I guess. I'm not a developer myself or an expert, but this is what I noticed right away.

A bit off-topic, but still related to the icons:
As you said and I agree 100%, icons are super important to quickly identify things. At least, I do feel that way.
The scripts are the only files I can customize the icons. I would like to do the same, for example for Quick Links, etc. 
Is this possible? Is there a place where all files are saved and I can go and add the icon?

**Comment by dehesa** [comment]
> The one on top is the one created and saved using the extension, the bottom one is created and saved using the Script Editor...

That is related to do Finder metadata added to the file by Script Editor. You can check the metadata in the terminal by typing `ls -l@`.

> As you said and I agree 100%, icons are super important to quickly identify things. At least, I do feel that way.
The scripts are the only files I can customize the icons. I would like to do the same, for example for Quick Links, etc.
Is this possible? Is there a place where all files are saved and I can go and add the icon.

Currently that is not supported for Quicklinks, but it is a feature we want to release fairly soon. Keep an eye into the Changelog in the following releases 😉

**Comment by iamdannywyatt** [comment]
Great to know that adding custom icons to Quicklinks (and maybe even other options, when possible) is something you will be implementing! I will for sure keep an eye on the Changelog. Appreciate it!
