### ISSUE TITLE
[feature] Argument support drop-down list

### ISSUE THREAD

**Issue by chsobin** [raycast/script-commands#792]
in some case, it is hard to input args quickly and correctly, so it may helpful when has drop-down list for user to select.

just like the drop-down list in extensions
<img width="750" alt="image" src="https://user-images.githubusercontent.com/30221890/202893658-38433b4b-d9f4-4156-a5a5-60b9626828a9.png">

**Comment by dehesa** [comment]
Hey @chsobin,

Thank you for the feedback. That is indeed something that would be good to have. The idea has already pop up a couple of times and I see a lot of value on it. I do want to implement it at some point, but to be honest, it won't be in the next 3 to 4 months. We have pretty big stuff coming and we are quite busy.

**Comment by chsobin** [comment]
@dehesa
