### ISSUE TITLE
Portuguese word with tilde gets encoded differently when run through script

### ISSUE THREAD

**Issue by raddevon** [raycast/script-commands#794]
Running Raycast 1.44.0

I wrote a script that takes a single argument which is intended to be a Portuguese word. It forms a URL using that word and opens it in the browser, but the word's encoding is different by the time it gets to the browser than it is if I paste the same value directly into the browser. I've tried writing the script as a bash script and as a Node script, and the result is the same. I suspect Raycast itself is encoding the value before it gets to my script. The result is the same whether argument encoding is on or off in the script itself.

Here's the word in question: `irmãos`

When I paste it directly into a URL in the browser, I get this: `irm%C3%A3os`
When I run it through Raycast and my script, it comes out like this: `irma%CC%83os`

The two variations appear identical in the address bar (as `irmãos`), but the URL formed with the first encoding works while the second does not.

**Comment by dehesa** [comment]
I will look into this. Could you also give me a minimal version of a script having the problem, please?

**Comment by raddevon** [comment]
Sure thing. The script is already pretty minimal. You'll need to install via `npm install open`.

```js
#!/usr/bin/env node

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Speak in Portuguese
// @raycast.mode compact

// Optional parameters:
// @raycast.icon 🤖
// @raycast.argument1 { "type": "text", "placeholder": "word" }

// Documentation:
// @raycast.description Searches for a recorded pronunciation of a work in European Portuguese
// @raycast.author Devon Campbell

const open = require("open");

const word = encodeURIComponent(process.argv.slice(2)[0]);
const firstChar = word.charAt(0);

open(
  `https://www.practiceportuguese.com/wp-content/uploads/portuguese/audio/${firstChar}/${word}.mp3`
);
```

Thanks for looking into it!

**Comment by raddevon** [comment]
Result is the same, by the way, even if I don't wrap the argument with `encodeURIComponent`.

**Comment by dehesa** [comment]
Hey there @raddevon, long time no see 😄 

I am very sorry this took so long and it was marked as stale. I have been looking into your issue and I am getting the expected result. That is, when you input `irmãos` on Raycast, the script receives `irmãos`. Could you run the following script with the argument `irmãos` and let me know what you get:

```bash
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Speak in Portuguese
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖
# @raycast.argument1 { "type": "text", "placeholder": "word" }

# Documentation:
# @raycast.description Searches for a recorded pronunciation of a word in European Portuguese
# @raycast.author Devon Campbell

echo $1
```

If you are getting something different, the problem would be with your system localization. I would suggest you change it system-wide or just override it for the shell script by adding the following line after the Raycast metadata.

```
LANG=en_US.UTF-8
```

Let me know if that worked.

**Comment by raddevon** [comment]
Thank you, @dehesa. My result is the same as I originally reported when I try your script, with or without `LANG=en_US.UTF-8` added at the top of the script.

Here's the modified script I tried (in addition to your original):
```bash
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Portuguese test
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖
# @raycast.argument1 { "type": "text", "placeholder": "word" }

# Documentation:
# @raycast.description Searches for a recorded pronunciation of a word in European Portuguese
# @raycast.author Devon Campbell

LANG=en_US.UTF-8
echo $1
```

The result of the script always appears as `irmãos`, but the encoding of the output seems to be incorrect. The `irmãos` coming out of your script is `irma%CC%83os` where it should instead be `irm%C3%A3os`.

Are you saying you were able to get my script to open the URL for the audio by pasting in `irmãos`, or is it just that the result _appears_ the same as the original when run through your echo script?


Here's the word I run through the script: `irmãos`
and here's what I get back: `irmãos`

The two look identical, but if you decode them, you'll see that they are not, which results in a 404 instead of a valid URL for my use case.

**Comment by dehesa** [comment]
I was definitely able to open the URL for the audio. I tried that!

I understand the difference of encoding and that they look similar to the eye (but they are internally different). But, as I said, I  was able to open the URL and listening to the audio. To be honest, I am not sure what it could be... 🤔
