### ISSUE TITLE
Network quality script stopped working

### ISSUE THREAD

**Issue by crstauf** [raycast/script-commands#795]
The [`networkQuality` script](https://github.com/raycast/script-commands/blob/master/commands/system/network-quality.sh) introduced by @LanikSJ in #715 appears to have stopped working.

macOS v13.0
Raycast v1.44.0

**Comment by dehesa** [comment]
Hey @crstauf, thank you for bringing this up and fixing it 😄 . Let's continue the conversation on the PR.
