### ISSUE TITLE
crypto-portfolio.py script stopped to work

### ISSUE THREAD

**Issue by rdanilin** [raycast/script-commands#797]
Response from "https://api.binance.com/api/v3/ticker/24hr?symbol=BNC":

```
{
    "code": 0,
    "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
```

**Comment by dehesa** [comment]
Hi @rdanilin,

Apologies for not answering this sooner. Could you give me more context in what is going on. Is this related to script-commands or something else?

**Comment by rdanilin** [comment]
I've installed a plugin to my local machine and tried to search a stock symbol. 
^^^ error appeared in Raycast.

**Comment by dehesa** [comment]
Oh, I see. You mean [this script-command](https://github.com/raycast/script-commands/blob/master/commands/dashboard/crypto-portfolio.py). This script was develop by @mehtamanan, maybe he is able to help out here.

**Comment by mehtamanan** [comment]
the script is using the binance api to get exchange rates, i can update the script this week to use a different api with no geo restrictions

**Comment by dehesa** [comment]
Any improvement you could make would be appreciated 😄

**Comment by dehesa** [comment]
Hey @mehtamanan, I am just checking in. Did you manage to change the api for no geo restrictions?

**Comment by dehesa** [comment]
I am closing this for now, since it has been more than a month without updates, but I am more than happy to reopen it later.
