### ISSUE TITLE
Should scan for parameters from head instead of tail.

### ISSUE THREAD

**Issue by UncleBill** [raycast/script-commands#798]
I have a script command to generate new ones, which have parameters descriptor in head of the file by default, then I see `raycast` show the title incorrectly.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1141198/206356871-a0904c3a-15db-490d-86be-c294921888ed.png">

If it put it after the code, it will show correctly.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/1141198/206356992-015823e4-ecb6-44ce-93af-82906ff57210.png">

**Comment by dehesa** [comment]
Hi @UncleBill,

Thank you for bringing this up and apologies for the delay answering the issue. This is a problem in how Raycast parses the script that I will try to fix soon, although I cannot give you an ETA yet, sorry.

**Comment by dehesa** [comment]
I have fixed this and it will be there in the next release (1.46.0). Let me know if you need anything else 😉
