### ISSUE TITLE
python script argument encode error with Chinese.

### ISSUE THREAD

**Issue by shuivin** [raycast/script-commands#802]
The script as blew:

```
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-


# Raycast Script Command Template
#
# Dependency: This script requires Python 3
# Install Python 3: https://www.python.org/downloads/release
#
# Duplicate this file and remove ".template." from the filename to get started.
# See full documentation here: https://github.com/raycast/script-commands
#
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title momo
# @raycast.mode fullOutput
# @raycast.packageName Raycast Scripts
#
# Optional parameters:
# @raycast.icon 🤖
# @raycast.currentDirectoryPath ~
# @raycast.needsConfirmation false
# @raycast.argument1 { "type": "text", "placeholder": "Name", "optional": false, "percentEncoded": true}
# @raycast.argument2 { "type": "text", "placeholder": "Content", "optional": true, "percentEncoded": true}
# @raycast.packageName Obsidian
#
# Documentation:
# @raycast.description 快速写一个笔记
# @raycast.author 
# @raycast.authorURL 



import sys, subprocess


print ('argument count:', len(sys.argv), 'argument')
print ('argument list :', str(sys.argv))
print(sys.argv[1])
print(sys.argv[2])

```

when i run it in mac M1, with terminal, the Chinese character test pass:

```
------------------------------------------------------------------------------------
~/Documents/Raycast/shell » ./momo.py 多大 西瓜
argument count: 3 argument
argument list : ['./momo.py', '多大', '西瓜']
多大
西瓜
------------------------------------------------------------------------------------
```

but call the script with raycast , the Chinese character  test NG.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/1046701/208912413-02a31688-b4bd-4ce5-9e3d-24f0e26b529d.png">

**Comment by shuivin** [comment]
i set  the percentEncoded to false, it works!
but why percentEncoded effect the Chinese character ?

**Comment by dehesa** [comment]
Uhm, this is weird. I will investigate and come back to you. Sorry for the inconveniences.

**Comment by dehesa** [comment]
Hey @shuivin,

I have been looking at your issue and I've concluded that Raycast is indeed doing what it is expected; that is, it is "percent encoding" your arguments.

The values you are receiving in your scripts are the standard percent encoded outcome. Therefore, if you want to retrieve the "regular" values, you should either:
- not define them as `percentEncoded` in the script metadata, or
- "percent decode" them yourself inside your script.

I don't know the function in python for this, but in Swift it is [`removingPercentEncoding`](https://developer.apple.com/documentation/foundation/nsstring/1409569-removingpercentencoding).

All this said, I went ahead and did some small changes in Raycast, to display the actual arguments in the full output. Displaying `Name: "%E5%A4%9A%E5%A4%A7", Content: "...."` is not very useful. Now I will display: `Name: "多大", Content: "西瓜" `. This will get out in the next release (1.46.0).

I hope this has been helpful. Let me know if you need anything else.

**Comment by shuivin** [comment]
@dehesa copy it!
I prefer to not  define as percentEncoded currently. 
Raycast is a awsome  tools for me .

**Comment by shuivin** [comment]
close the issue
