### ISSUE TITLE
Toggle microphone (input volume) in system commands

### ISSUE THREAD

**Issue by Dammmien** [raycast/script-commands#804]
Hello,

I see there is a script about mute / unmute the microphone input [here](https://github.com/raycast/script-commands/blob/master/commands/system/audio/toggle-mic.applescript) but I can't find it in the app:

![Capture d’écran 2023-01-03 à 12 18 27](https://user-images.githubusercontent.com/3051737/210347326-a33b9c20-c9e7-407a-854c-75b52ed2d3c4.png)

The toggle mute is for output not input. How can I enable toggle mic command ?

**Comment by dehesa** [comment]
Hi @Dammmien,

Those scripts come bundled within Raycast and sadly the "muting mic" is not in there. However, the Raycast Community picked up the challenge and wrote some extra [audio functionality](https://github.com/raycast/script-commands/tree/master/commands/system/audio) you can easily install.

I believe the one you want is [this one](https://github.com/raycast/script-commands/blob/master/commands/system/audio/toggle-mic.applescript).
