### ISSUE TITLE
is there some method to call clipboard history window while  at the main raycast input window?

### ISSUE THREAD

**Issue by 668168** [raycast/script-commands#807]
For Example:
In the Input window,  I want to input something from the clipboard history. 
but when i use the Hotkey to call the clipboard history window, the Input window has disappeared. 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1046701/212811485-fe38be2d-7338-463a-9dbe-19459b2d9a5d.png">

**Comment by dehesa** [comment]
Hi @668168,

This repo is exclusively for Script Commands (as we point out in the README file). We try to keep this clean for just that. If you have any questions on regular Raycast usage, please [send us an email](mailto:feedback@raycast.com), use the feedback command within Raycast, or (even better) join the [Slack community](https://www.raycast.com/community).
