### ISSUE TITLE
Clipboard History: Disabled Applications not working

### ISSUE THREAD

**Issue by dferber90** [raycast/script-commands#827]
I have Keychain Access set as a disabled application for Clipboard History

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1765075/221751613-44372d2a-d2bc-4569-b80e-e40c4f8d6e52.png">

But whenever I copy from Keychain Access the content actually shows up in Clipboard History.

I believe this is due to my system language being set to german.

The Keychain Access application is called Schlüsselbundverwaltung when used in german. Are you maybe depending on the name of the application somewhere?

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1765075/221751796-2595826f-b2a7-487f-98c8-7b96df02537d.png">

If I attempt to add the Schlüsselbundverwaltung application in the Clipboard History settings it still shows up as "Keychain Access", so I can't add the german version to the ignored list.

**Comment by dehesa** [comment]
Hey @dferber90,

This repo is exclusively for issues and PR related to Scripts Commands (as we state in the README), for anything else Raycast related, please [send us an email](mailto:feedback@raycast.com), use the feedback command within Raycast, or join the [Slack community](https://www.raycast.com/community).

**Comment by dehesa** [comment]
Sorry if this looked a bit too cold @dferber90,

We try to keep Github repos very explicit to their intended usages. The [extensions repo](https://github.com/raycast/extensions) for the development of Raycast Extensions and [this repo](https://github.com/raycast/script-commands) for the development of script commands. This makes it easy for people having issues developing script commands, to come here and quickly look if their issue has a solution. At the same time, it makes it easy for use to manage more low-level programming questions than the typical user questions.

We do try to be very open with user feedback and we have a lot of ways for users to write to us (email, twitter, mastodon, slack, and feedback command within Raycast). I hope this makes sense.
