### ISSUE TITLE
Define Word can not show the pronunciation button

### ISSUE THREAD

**Issue by shaneing** [raycast/script-commands#828]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/14818134/222469263-08bbe02d-493c-4ed9-bcc0-e89c1496fe30.png">

**Comment by dehesa** [comment]
Hey @shaneing,

This repo is exclusively for issues and PR related to Scripts Commands (as we state in the [README](https://github.com/raycast/script-commands/blob/master/README.md)), for anything else Raycast related, please [send us an email](mailto:feedback@raycast.com), use the feedback command within Raycast, write a DM or post something in [Twitter](https://twitter.com/raycastapp) or [Mastodon](https://mastodon.social/@raycast), or join the [Slack community](https://www.raycast.com/community).
