### ISSUE TITLE
Can't get system variables in Python script.

### ISSUE THREAD

**Issue by realskyrin** [raycast/script-commands#830]
I want to run a Python script which will get some system variables. It works normally in terminal but not in Raycast.

<img width="1371" alt="WeChat3d41b91e5ab42acb42b6f163992c49bc" src="https://user-images.githubusercontent.com/16552732/224487165-405e67b9-cf98-4b7e-936b-cdbc6e165857.png">

**Comment by dehesa** [comment]
I believed that is due to the non-login shell described in the README, check it out.

<img width="695" alt="README screenshot" src="https://user-images.githubusercontent.com/684318/224708103-0fd05e71-956f-40cc-9ed7-67134c931a58.png">
