### ISSUE TITLE
`refreshTime` just not refreshing. Help needed debugging please

### ISSUE THREAD

**Issue by whomwah** [raycast/script-commands#831]
Hi 👋 

I'm having trouble seeing `refreshTime` work at all unless I manually refresh. I've ended up using the template created by Raycast below to reduce it as simply as I can but still still no joy. I see in the documentation it mentions a max number of `inline` uses:

<img width="960" alt="CleanShot 2023-03-16 at 10 21 43@2x" src="https://user-images.githubusercontent.com/2031/225587802-a239fcf9-57fb-452f-918e-b8415db1cb99.png">

But I've only created one script myself. Does this value include scripts provided by other people and if so how would I go about checking this to see if it's the issue? It's a great feature which I'd really like to use without having to do anything manually.

```
#!/usr/bin node

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Test
// @raycast.mode inline
// @raycast.refreshTime 30s

// Optional parameters:
// @raycast.icon 🤖

console.log(`Hello World! ${Math.floor(Math.random() * 101)}`)
```

### other details

![CleanShot 2023-03-16 at 10 26 39@2x](https://user-images.githubusercontent.com/2031/225588994-fd6db53d-94c8-4757-b813-10659e0ba2a1.png)

![CleanShot 2023-03-16 at 10 29 03@2x](https://user-images.githubusercontent.com/2031/225589643-93ceb5ae-04e0-4e19-bf89-066c2084c0bb.png)

**Comment by crstauf** [comment]
Yes, Raycast supports a maximum of 10 scripts with auto-refresh, regardless of the author.

**Comment by whomwah** [comment]
@crstauf Can an extension contain script commands? As I've only created one for myself.

**Comment by crstauf** [comment]
@whomwah I'm not a React dev, so I'm not sure. Sorry.

**Comment by whomwah** [comment]
So I've been through this with one of the Raycast team and whilst I didn't find exactly what the issue was, something in the testing, restarting of the app and updating has caused the `refreshTime` to start working again as expected so I will carry on an keep track in case it happens again. In the mean time I'm going to close this issue.
