### ISSUE TITLE
Raycast for Windows OS

### ISSUE THREAD

**Issue by DZ8540** [raycast/script-commands#834]
Is the `Raycast` planned on `Windows`? I am sure that it would be very useful for `Windows` users, and even for `Linux`.

**Comment by dehesa** [comment]
Hey there @DZ8540,

This repo is used exclusively for script commands. For anything that is not related to script commands, please [send us an email](mailto:feedback@raycast.com), use the feedback command within Raycast, or join the [Slack community](https://www.raycast.com/community).

But quickly answering your question, we will love to develop a Windows and/or Linux version at some point. But to tell you the truth it won't happen anytime soon.

**Comment by eevmanu** [comment]
related #10
