### ISSUE TITLE
How to delete a script

### ISSUE THREAD

**Issue by DutchPete** [raycast/script-commands#835]
I have a script that I want to delete, but there does not seem to be a way to do so. ⌘+K does not give the pop-up window, right-clicking does not work either. What am I missing?

**Comment by dehesa** [comment]
Hi @DutchPete,

There is an action inside the ⌘+K menu called "Move to trash". It is at the very bottom. I just tested it out and it works as expected.

If you don't see it, I would appreciate a screencast or some screenshots with your problem. If you are not comfortable sending them here, please sent me a DM in the [Slack community](https://www.raycast.com/community) or [send us an email](mailto:feedback@raycast.com).

**Comment by DutchPete** [comment]
Hello @dehesa,

Many thanks for your feedback. I was aware of that possibility, and, like I mentioned above, I tried it, and even tried it again just now.

The problem is that when I do `⌘+K` I just hear a “bloop” kind of sound, but the menu pop-up does not appear. The script is the `Search Emojis` one.

![image](https://user-images.githubusercontent.com/10794265/231494870-7bacf7c0-8e81-460e-947f-a1192f83d277.png)

**Comment by dehesa** [comment]
Uhm, that indeed shouldn't happen. Does the "Move to Trash" option appear for the other scripts?

Could you send another screenshot with the "Script Commands" selected. Similar to this one below.

<img width="1112" alt="Script Commands options" src="https://user-images.githubusercontent.com/684318/231496337-121ff30c-9c33-4ec7-8d4c-2c7bc13f608f.png">

I would also appreciate if you can send me the exact script file (not just copy-paste it here). Sometimes there are problems with the file encoding 🤔

**Comment by DutchPete** [comment]
`⌘+K` does not work on any of the scripts. Here is the screenshot again:

![image](https://user-images.githubusercontent.com/10794265/231498257-12639c3c-21b1-486c-bd2a-70a9b26da0d5.png)

I think I know where you are heading: to see where the scripts are stored. They are in my VeraCrypt vault. They all work fine, except this one, which is why I want to get rid of it.

And here is the file:
[emojis-search.sh.zip](https://github.com/raycast/script-commands/files/11212845/emojis-search.sh.zip)

**Comment by dehesa** [comment]
I was indeed trying to know your script commands sources. The information you now provided seems to point to the issue and that seems to be that the scripts are not correctly "interacted" with the source folder. To verify this assumption, would you mind:
- creating a temporary folder somewhere in your user folder,
- copy-pasting all the scripts there,
- remove the `36` folder from the script commands directories in Raycast,
- add the newly created temporary folder,
- interact with those files and see whether it works.

**Comment by dehesa** [comment]
Ok, that is definitely odd and it is probably Raycast fault. Could you do the following and send me the results. I will try to figure out the problem in the codebase.

1. Continue with the new folder in `~/Scripts-Raycast` (not the previous `36`)
2. Quit Raycast completely.
3. Print into a file Raycast's logs using [this command](https://manual.raycast.com/troubleshooting/getting-logs-via-consoleapp).
4. Launch Raycast.
5. Open Raycast settings, look that the folder `~/Scripts-Raycast` is still there.
6. Open Raycast (⌘+space or whatever you have assigned) and look for one of your scripts (e.g. `Search Emojis`).
7. Press ⌘+K or use the mouse (do tell me if you actually see the "Actions ⌘+K button).

PS: I had to google what the "Johnny Decimal" system is 😆

**Comment by DutchPete** [comment]
@dehesa sorry for the late reply, I was called away.

I went through all the steps: yes, the folder (step 5) is still there. Yes, the “Actions ⌘+K” button is there.

Now, it seems I may have been invoking `⌘+K` the wrong way. It seems that the right way is:
1. Press `⌘+Space` to bring up Raycast's Spotlight-type box
2. Press `⌘+K` to bring up the list of commands, scripts and quicklinks. On the right of that box there is also a pop-up that you can dismiss with `Esc`
3. Scroll through the list, click on the relevant command/script/quicklink, and press `⌘+K` to edit, delete, whatever.

What I was doing after step 1 is to press `⌘+,`, then go to one of the tabs, click on the relevant command, script or quicklink, then press `⌘+K` for editing. From what I remember that was working, but now I get the “bloop”.

Anyway, here is the log file:
[ray.20230413_073340.log](https://github.com/raycast/script-commands/files/11218355/ray.20230413_073340.log)

**Comment by dehesa** [comment]
Oh, I see. As far as I am aware "Raycast Settings > Extensions" have never supported ⌘+K interaction. You could, however, right click on that screen in any of your script commands to delete them, show them in finder, or open them in your default editor.

Glad we finally got at the bottom of it. I will close this issue for now, but feel free to reopen it or ask more questions.

**Comment by DutchPete** [comment]
> You could, however, right click on that screen in any of your script commands to delete them, show them in finder, or open them in your default editor.

Just for the record, that does not work for me, like I said in my OP. Anyway, we can leave this closed.

Many thanks for your help and patience.
