### ISSUE TITLE
Markdown Table support in fullOutput

### ISSUE THREAD

**Issue by aschilling** [raycast/script-commands#837]
Hi everybody,

congratulations for Raycast, it is a great app. In the release notes of Raycast v1.50.0 you write "Markdown Tables are now properly supported everywhere." But this does not include the fullOutput mode of Script Commands, right?

Is this a bug? It would be great if markdown tables are also supported for script commands.

Best 
Andy

**Comment by dehesa** [comment]
Hey @aschilling,

You are correct, that is currently not supported in the `fullOutput` mode of Script Commands. I will write it down on our task system. Thank you for bringing it up.
