### ISSUE TITLE
Why the new version of Raycast script cannot send text to clipboard?

### ISSUE THREAD

**Issue by baker221** [raycast/script-commands#842]
I write a Python script of OCR.
The beginning part of script:
```
#!/usr/bin/env python3

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title ocr
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 
```

The clipboard operation part:
```python
    import pyperclip
    pyperclip.copy(content)
    print("Success!")
```
In the old version, this works well. But now (version 1.51.3) after running it, the clipboard is still empty.

But when I run it in console, this works well.

The bash command of `pbcopy` or something cannot operate correctly now

**Comment by baker221** [comment]
I also test the following:
``` Python
    import pyperclip
    pyperclip.copy(content)
    print(pyperclip.paste())
```
The output is empty if the content has Chinese.

But if I just print it:
```python
    print("你好")
```
This can work and display.

**Comment by baker221** [comment]
I write a new simple script and I am confirmed that this is the problem of new version Raycast.

```bash
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title mytest
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 📋

# Documentation:
# @raycast.description hello

#echo "haha" | pbcopy # works
echo "你好" | pbcopy # do not work
echo "Clipboard emptied"
```

**Comment by YHsilver** [comment]
same problem  for me

**Comment by dehesa** [comment]
Hey @baker221 and @YHsilver,

Thank you for writing and sorry this took long to answer. I just tried your script and everything works as expected (see below).

<img width="862" alt="Terminal" src="https://github.com/raycast/script-commands/assets/684318/7e352413-2a9f-4b39-8ccf-07d3e10a534b">

It looks like it has something to do with the terminal environment. Can you think of anyway I can replicate?

**Comment by baker221** [comment]
> Hey @baker221 and @YHsilver,
> 
> Thank you for writing and sorry this took long to answer. I just tried your script and everything works as expected (see below).
> 
> <img alt="Terminal" width="862" src="https://user-images.githubusercontent.com/684318/241925321-7e352413-2a9f-4b39-8ccf-07d3e10a534b.png">
> It looks like it has something to do with the terminal environment. Can you think of anyway I can replicate?

I see that the "character" is 3. But "你好" just have 2 characters. If I copy "你好" directly, the character is 2. (But even if I added a space before this string, the script still cannot work)
<img width="774" alt="Snipaste_2023-05-30_18-53-25" src="https://github.com/raycast/script-commands/assets/43471538/c365c90a-4a51-45e9-9540-a3e12ab4c64c">

**Comment by baker221** [comment]
Do you have any idea solving this issue until now? This version (1.54.1) still cannot work.

**Comment by baker221** [comment]
Still no solution? @dehesa

**Comment by baker221** [comment]
> Still no solution? @dehesa

I found that. The Raycast's locale somehow changed in a new version.

Change the `pbcopy` into below:
```bash
echo "你好" | LANG=zh_CN.UTF-8 pbcopy
```
