### ISSUE TITLE
highjacks current terminal window instead of opening new terminal window

### ISSUE THREAD

**Issue by joeldcanfield** [raycast/script-commands#844]
I'm going to edit my own copy of the script, but it was disconcerting to have my currently open terminal window preempted when I ran this script in Raycast.

**Comment by dehesa** [comment]
Hi @joeldcanfield,

Thanks for writing with feedback; however I am not sure I understand what you mean. Let me see if I get it:
1. You edit a script with a common editor (e.g. Visual Studio Code).
2. You save the edited script.
3. Then what?

**Comment by joeldcanfield** [comment]
Wow; not sure how I got so lost. This was intended as feedback on a particular script I like, and somehow wound up in the root discuss. Apologies. Thanks for waking me up ;)
