### ISSUE TITLE
allow recursive search in script directory

### ISSUE THREAD

**Issue by hereisderek** [raycast/script-commands#849]

**Comment by unnamedd** [comment]
Hi @hereisderek, 

this is not related to the Script Commands itself. What you are asking is a feature for Raycast, for that, I highly recommend you to use the [Raycast Community](https://raycast.com/community) or the "Send Feedback" from inside of Raycast to do so.

Before I forget to mention: this is already requested some times in the past and they already explained the reasons behind of the decision to not implement the recursive search.
