### ISSUE TITLE
"Running script" continues indefinitely

### ISSUE THREAD

**Issue by tomelliot** [raycast/script-commands#857]
Hi there,

I have a handful of really simple scripts that I use as shortcuts to open finder at a specific location. I find that later when I reopen Raycast, it still tells me it's running that script I used ages ago. 

I'm not sure if that's expected behaviour, or a bug. I'm open to other suggestions if someone has a better way of achieving the same thing. Here's an example script:

```
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open Downloads
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖

open /Users/me/Downloads
exit
```

**Comment by benhoh** [comment]
I've found that setting the mode to "silent" avoids this.

**Comment by tomelliot** [comment]
Thanks - I'll give it a try
