### ISSUE TITLE
After running a command, next launch should show initial screen

### ISSUE THREAD

**Issue by isakkeyten** [raycast/script-commands#86]
Example

Launch raycast
type myschedule
hit enter
choose an event
hit enter to open it
raycast is closed and action is done

Launch raycast for completely different purpose
screen is still on calendar view with selected calendar event as before
now the user has to tap esc twice in order to go back to screen one where he can search for another action to perform

**Comment by thomaspaulmann** [comment]
Hey @isakkeyten, this repository is not meant to report bugs. It's a place for sharing script commands. The behavior is on purpose to prevent context loss. However, we do reset the screen after a while or when you perform certain actions. Additionally we shipped a feature preview in v1.2.0 that allows you to always show the initial screen. Please check it out.

For future bug reports, please use the in-app feedback command or join our [Slack](https://www.raycast.com/community) community. Thanks.
