### ISSUE TITLE
I hope to set the default value and memory ability.

### ISSUE THREAD

**Issue by zxpzdtom** [raycast/script-commands#865]
![image](https://github.com/raycast/script-commands/assets/22407004/e8c831f3-9651-4fd2-a9c8-2f107fbbe6f5)

![image](https://github.com/raycast/script-commands/assets/22407004/dac05660-d8d3-4665-a0c3-6797def2c58f)

**Comment by unnamedd** [comment]
It is not possible to define a visible default value for the placeholder in the root search list, you will have to define it optional true and inside of your Script Command make a check, in case it is empty, you use the default value.

I highly recommend you to give a check in this [document](https://github.com/raycast/script-commands/blob/master/documentation/ARGUMENTS.md).

**Comment by zxpzdtom** [comment]
Thanks
