### ISSUE TITLE
AppleScript missing icons

### ISSUE THREAD

**Issue by niemtec** [raycast/script-commands#868]
When creating a new AppleScript (saved with either default Mac Roman or UTF-8 encoding) and setting the `@raycast.icon` parameter with a path to a local `.png` file (downloaded from the official Raycast Icon Maker), the script doesn't show the icon in Raycast window. 

Script snippet: 
`# @raycast.icon ./raycast/icons/calendar.png`

Raycast panel
![image](https://github.com/raycast/script-commands/assets/10573413/ab83f171-a31d-4ee2-979b-ca8ddb92011b)

As per image above, Raycast doesn't display the icon that's referenced in the script.

**Comment by dehesa** [comment]
Uhm, I just tried in my machine and I am able to see the icon no problem.

Would you mind checking if you are having a similar issue to #769. I know you can execute the script, but try to follow those steps anyways.

If it doesn't work, please pass here your script and the icon so I can try it out.
