### ISSUE TITLE
Can't stop script from running in the background

### ISSUE THREAD

**Issue by mauriedo-tgo** [raycast/script-commands#870]
Hi, strange issue ahead:

- I was trying to develop a simple script to get the current date in my clipboard
- At some point I added an alias (I think) of `date` but something was wrong with the script (it was replacing the word `date` instead)
- Now I can't stop the script in its "wrong" version from running every time I type `date`
- I've disabled it, deleted the files, deleted the script location, uninstalled Raycast (doesn't work because uninstalling doesn't delete user files, it picks up the same settings as before uninstalling) yet the problem persists.

100% Raycast related, as when Raycast is off, the issue doesn't happen anymore.

I got the logs, but nothing much in there, only that "date" was removed at that time, but still there somehow:

```
Filtering the log data using "subsystem == "com.raycast.macos""
Timestamp               Ty Process[PID:TID]
2023-08-20 11:02:27.819 Db Raycast[1421:2d23] [com.raycast.macos:snippets] Snippet injection request created
		Alias: date
		Delay (pre-injection): 0.2
2023-08-20 11:02:29.065 Db Raycast[1421:2c05] [com.raycast.macos:snippets] Snippet injection request succeeded
		Alias: date
```

Help please, I don't want to stop using Raycast for this, but it is seriously impacting me.

Thanks :)

**Comment by unnamedd** [comment]
may @dehesa would you give a little help in here

**Comment by dehesa** [comment]
Hi @mauriedo-tgo,

Sorry it took so long to answer. I've been on holidays 😬 Let me see if I got this correctly:
- You developed a script and set it an alias called `date`.
- You removed the script.
- Now, every time you write the word `date`, the script executes?

What it is confusing to me is that the log you paste shows a "Snippet" injection, no script.

**Comment by mauriedo-tgo** [comment]
Hi Marcos, yes your understanding is correct, I am as puzzled as you are.

**Comment by dehesa** [comment]
That is indeed very odd 😅 The snippet engine and the script-command service are completely independent systems. I must ask: Are you completely sure you don't have any snippet in `Search Snippets` command with the keyword `date`? Could you double check for me?

If the problem persists, I would appreciate the following info:
- macOS version, raycast version, and whether you are in an ARM or Intel machine.
- How many snippets do you have?
- How many scripts does Raycast observe?

By the way, you can see how to completely uninstall Raycast in our [manual](https://manual.raycast.com/) (at the very end).

**Comment by mauriedo-tgo** [comment]
I uninstalled it after raising this ticket so I can't answer straight away,
I think you can close this ticket for now and I will reopen or raise a new
one when I install again if I run into the same ghostly issues. Thanks!
