### ISSUE TITLE
default-browser-XXX scripts - Mac OS Sonoma

### ISSUE THREAD

**Issue by antonynghiem** [raycast/script-commands#883]
https://github.com/raycast/script-commands/blame/e9dfe433609693145eee35f3befb70325fa8f64b/commands/system/default-browser-safari.applescript#L25-L31

In Mac OS Sonoma, the confirmation of the default browser selection has changed to 1 (is 2 now)

**Comment by dehesa** [comment]
Hey @antonynghiem,

Very sorry it took so long to answer. I am running Sonoma and the current Script is working for me. The button is still `2` as far as I can see.

**Comment by dehesa** [comment]
![Permission](https://github.com/raycast/script-commands/assets/684318/8108295c-da31-46ee-afb3-73d88e111e87)

**Comment by antonynghiem** [comment]
Hey @dehesa ! No worries. Maybe its then langauge specific? :D. In german the buttons are vertical aligned:

<img width="296" alt="image" src="https://github.com/raycast/script-commands/assets/9560414/4a841196-febd-4855-b8fd-ea17828162cd">

**Comment by dehesa** [comment]
Oh, interesting, but yeah you will need to change the script for your own case.
