### ISSUE TITLE
Default browser scripts not working on Sonoma

### ISSUE THREAD

**Issue by scottaw66** [raycast/script-commands#897]
I can run the default browser scripts directly from the AppleScript Script Editor and they run fine, but running the script commands for them in Raycast gives me an "Error: Process tried to run, but failed" error message.

**Comment by Iron0utlaw** [comment]
I think you can get a more elaborate error message on copying the error log using `cmd+T`

**Comment by dehesa** [comment]
You are probably running into [this problem](https://github.com/raycast/script-commands/issues/769). Please try the solution there and let us know if that works.

**Comment by scottaw66** [comment]
Yep, that was 100% it. Thank you!

**Comment by scottaw66** [comment]
Now my problem is that it pops up a dialog asking if I want to change or keep the current browser, and it's getting auto-submitted to keep the current one.

<img width="372" alt="image" src="https://github.com/raycast/script-commands/assets/7348442/5dc84f46-64f4-4ad7-8e78-f542f3e369d8">

**Comment by scottaw66** [comment]
Oh, I bet it's the button 2 thing...
