### ISSUE TITLE
Open vim with script commands

### ISSUE THREAD

**Issue by Rukenshia** [raycast/script-commands#9]
Hi there,

I have a workflow for note taking, where I have two scripts - `note` and `edit-note`, which open (neo)vim, and then commit any changes to my git repository. It seems like using script commands in raycast does not support it, with vim complaining it is not running in a terminal.
Have you thought in general how workflows like this could be supported? I understand it's probably hard to get this to work right, but wanted to voice that I definitely would love to have that integrated into Raycast.

**Comment by thomaspaulmann** [comment]
Do I understand correct that you would like to have a similar behavior then setting the `editor` in your terminal? This isn't really on how we envision Raycast. We would rather allow you to have a form/textfield that you can enter a note and then have a script that interprets it. This should work very nice with your workflow and allows for quickly jotting down notes. Do you use any specific CLI tool for your notes?

**Comment by Rukenshia** [comment]
The script opens my $EDITOR, so when I type `note`, it automatically opens a markdown file with the current date. Usually notes are more than one line, so I'm not sure if having a single lined text field will help me with this. The value of the script for me comes from wrapping everything for me and pushing the notes to my git repository after I'm done editing, and I thought it would be cool if I don't need to have my terminal open and instead could invoke it from Raycast.

**Comment by thomaspaulmann** [comment]
Coming back to this after some more thoughts... Raycast is meant for quick access to your tools. The use case you're mentioning is a great fit for this. However, we want to keep the UX consistent across all extensions. It would feel weird to pop an external editor to perform a text input. This should be built into Raycast as we have it for other forms, e.g. the `Create Reminder` command. 

However, we don't have this functionality for script commands. This is more in line with our [extensions API](https://raycast.com/developer-program) that will allow you to build feature rich extensions such as our built-in ones, e.g. Jira.  I'll close this issue as it doesn't fit script commands but would urge you to sign up for our [developer program](https://raycast.com/developer-program) to be amongst the first to experience our API. With it, you should be able to build a form for your note taking use case.
