### ISSUE TITLE
Clipboard content not getting set to the 1st Argument in Apple Music Search

### ISSUE THREAD

**Issue by amit-coditas** [raycast/script-commands#901]
Clipboard content not getting set to the 1st Argument in Apple Music Search - Remains blank and forces manual paste. 

<img width="751" alt="image" src="https://github.com/raycast/script-commands/assets/19991098/eac1954d-db68-41f1-a19a-a4b29c2c1049">

**Comment by dehesa** [comment]
Hey there @amit-coditas,

Is this the Apple Music Script-Command or is that the extension in the store? If it is related to the Script-Command, maybe @StevenRCE0 can help here since he is the author. In any case, I will suggest you to try the Apple Music Store extension?

**Comment by amit-coditas** [comment]
I do have the extension installed, but it doesn't have the 'search' option at all, hence was trying out the script. 

@StevenRCE0 would it be possible to have a quick look? thank you for your help!!

**Comment by StevenRCE0** [comment]
Thanks for your feedback. Just to make it clear, are you referring to what you input in the 1st argument did not paste into the music app as expected? (That's how it work, really straight forward: save your clipboard, copy the argument, reveal the Music app, paste into the search box, restore your clipboard) If this happens, it could be a hassle. However, if you're expecting what you've copied automatically appear in the argument's field, the behaviour is handled by Raycast.

**Comment by amit-coditas** [comment]
Hello @StevenRCE0 , 

thank you for the reply. I understand now, you are using the clipboard to 'transfer' what was passed in the argument/text in raycast to Apple Music app. 

I was hoping of a workflow where I see a song or an artist on any webpage (for e.g. Reddit), I copy the song name or Artist Name, and fire a workflow on raycast which then takes me to apple music, does a Ctrl V and makes the search (Basically avoiding an extra CTRL + V in Raycast)

**Comment by StevenRCE0** [comment]
For this use case, you may find Raycast's Quicklink helpful. To get it working, copy the Deeplink of the script command, and create a Quicklink like this:

`raycast://script-commands/apple-music-search?arguments={Query}`

Make sure you've turned on `Pass selected text as argument` under `Raycast settings` -> `Extensions` -> `Quicklinks`. After setting the whole thing up, just select any text on the web page for example, press the shortcut (no CTRL+V needed!), and it'll do.
