### ISSUE TITLE
Next Desktop not working

### ISSUE THREAD

**Issue by YusufLisawi** [raycast/script-commands#940]
I'm using macbook air m1, the move to next desktop is not moving the window, it's only switch to next desktop without moving the window i want

**Comment by dehesa** [comment]
Could you paste the link of the script you mean here?

**Comment by unnamedd** [comment]
@YusufLisawi looks like you are talking about the Next Desktop, which is part of the Window Management. The Window Management is a built-in extension of Raycast, that means, if you need to report some kind of bug you do have two options:

First; access our [Slack community](https://raycast.com/community) and use the channel #bugs for that
Second; use the **Send Feedback** form which is going to be accessed from your Raycast root search.

In any case, your issue doesn't fit well to this repository, as it doesn't seem related to Script Commands, therefore I am closing this issue.

If you do need any further help, please let us know! ;)
