### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by xiaooojun** [raycast/script-commands#941]
In practice, the Ruby version of the system will be used by default to execute relevant commands.

**Comment by dehesa** [comment]
That is true. What are your expectations?

**Comment by xiaooojun** [comment]
> That is true. What are your expectations?

I expect it to be consistent with the version of the terminal tool, because I want to move some commands that need to be executed in the terminal to raycast. Thank you very much...

**Comment by unnamedd** [comment]
@xiaooojun Raycast doesn't embed any kind of compiler/interpreter into their bundle, therefore, everything you are seeing related to Ruby version (or whatever software) it is all yours.

As this issue is not related to any Script Command we have in the repository, I am closing it. Feel free to make a comment if you need a further help.

**Comment by xiaooojun** [comment]
The same script file runs perfectly on the terminal, but when it runs through raycast's footsteps function, it always reports Ruby version problems. Whether it's python or bash,

**Comment by unnamedd** [comment]
Mind to share a screenshot here? At least @dehesa can have a better idea of what's happening. Unfortunately the messages exchanged here wasn't really helpful to allow any of us to provide a better help.

**Comment by xiaooojun** [comment]
I found the reason. Executing the script from raycast is a separate shell environment that will not take environment variable configuration files such as .zshrc, resulting in the priority configuration of the environment variable path not taking effect.

**Comment by unnamedd** [comment]
@xiaooojun that is totally correct and also documented on our README in the [Troubleshooting and FAQs](https://github.com/raycast/script-commands?tab=readme-ov-file#troubleshooting-and-faqs) section.

**Comment by xiaooojun** [comment]
> @xiaooojun that is totally correct and also documented on our README in the [Troubleshooting and FAQs](https://github.com/raycast/script-commands?tab=readme-ov-file#troubleshooting-and-faqs) section.
thank you very munch
