### ISSUE TITLE
is multiple line of script argument supported?

### ISSUE THREAD

**Issue by zcfan** [raycast/script-commands#943]
I have a dropdown argument with a plenty of options:

```bash
# @raycast.argument1 { "type": "dropdown", "placeholder": "Project", "data": [{"title": "111", "value": "https://xxx.xxx"}, {"title": "222", "value": "https://xxx.xxx"}, {"title": "333", "value": "https://xxx.xxx"}, ...] }
```

As you can see, I place them all in a single line which is hard to read.

I wonder can we format it into multiple lines, to enhance readability, I didn't find anything useful in documentation.

**Comment by dehesa** [comment]
Sadly not currently, I will add your comment as feature request internally.
