### ISSUE TITLE
Dynamic dropdown options

### ISSUE THREAD

**Issue by arielpollack** [raycast/script-commands#948]
It would be amazing to have the option to have a dynamic dropdown options.

My use case is that I have many script commands for using `git`, and it would be really helpful to list all my local branches to perform an action on.

Thanks!

**Comment by unnamedd** [comment]
Hi @arielpollack,

This repository is meant to receive issues regarding problems related to Script Commands. As you are suggesting an improvement to Raycast (even though it is associated with Script Commands), the best ways to do so are:

1. Go to our [Raycast Slack Community](https://raycast.com/community) and post your suggestion in the channel #suggestions, or
2. Use the Send Feedback form to submit it using the option Feature Request. You can access it from your root search.
![image](https://github.com/raycast/script-commands/assets/83694/62fbc9de-cc59-48fa-bcb4-5657b9852902)

These are the only two ways where you can have your voice heard (and it will be) by the team. They will add it to their internal system.

With all that being said, I am closing this issue.
Please, let me know if you need any further assistance.
