### ISSUE TITLE
Character encoding broken

### ISSUE THREAD

**Issue by VladimirFokow** [raycast/script-commands#953]
When copying non-English characters (specifically, Ukrainian) from/to the clipboard, the encoding is broken.
 
To reproduce:

Install [pyperclip](https://pypi.org/project/pyperclip/):
```bash
pip install pyperclip
```

Write a simple python script, e.g.:
```py
import pyperclip

text = pyperclip.paste()  # text is whatever is in the clipboard
pyperclip.copy(text)  # save text to clipboard
```

Copy some Ukrainian characters to your clipboard, e.g.: `тест`

When the script is run from the terminal, e.g. `python script.py`, it works fine: it saves to the clipboard the same thing that was there.

When it's run as the raycast "Script Command", it saves this to the clipboard: `????`

If I change the script so that it doesn't get text from the clipboard but instead saves "тест" to clipboard directly: `pyperclip.copy('тест')`, then I get this in my clipboard: `—Ç–µ—Å—Ç`

**Comment by dehesa** [comment]
Hey there @VladimirFokow,

Sorry to hear you are having issues. I am sadly not very knowledgeable with Python. We have had similar problems before, but to be honest I don't know what the issue could be. [Here](https://github.com/raycast/script-commands/issues/937#issuecomment-2124224710) is what I said to a previous user.

**Comment by VladimirFokow** [comment]
Hi, thanks for the reply..
Just tested it with bash, same problem:

```bash
#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title test_cp
# @raycast.mode silent
# @raycast.author Vladimir Fokow
# @raycast.description Test the clipboard
# @raycast.packageName test_cp
# @raycast.icon 🧪


# Save the content of the clipboard into a variable text
text=$(pbpaste)
# Save the content of variable text back into the clipboard
echo "$text" | pbcopy

# Example non-English characters to copy: тест
# result in the clipboard: ????





# # Alternative test:
# text='тест'
# echo "$text" | pbcopy
# # result in the clipboard: —Ç–µ—Å—Ç
```

**Comment by unnamedd** [comment]
@VladimirFokow to me, sounds very likely as a UTF-8 unicode problem. 
Using the example you provided:
```python
import pyperclip

text = pyperclip.paste()  # text is whatever is in the clipboard
pyperclip.copy(text)  # save text to clipboard
```

give a try in this piece of code and let us know if it will work for you

```python
import pyperclip
import os
import chardet

# Ensure the environment uses UTF-8 encoding
os.environ['PYTHONIOENCODING'] = 'utf-8'

# Function to detect and convert encoding
def convert_to_utf8(text):
    result = chardet.detect(text.encode())
    encoding = result['encoding']
    return text.encode(encoding).decode('utf-8')

# Get text from clipboard
text = pyperclip.paste()

# Convert text to UTF-8
text_utf8 = convert_to_utf8(text)

# Copy text back to clipboard
pyperclip.copy(text_utf8)

print("Text successfully copied to clipboard.")
```

**Comment by VladimirFokow** [comment]
hi @unnamedd , it didn't help.. same problem

For experimenting, here is an example "Script Command" which can invoke a python script
```py
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title test_cp_py
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.description Test the clipboard (Python)
# @raycast.packageName test_cp_py
# @raycast.icon 🐍

/path/to/python /path/to/script.py
```

**Comment by VladimirFokow** [comment]
Hi, could someone please point me at the code where the subprocess is created? Thanks!

[quote](https://github.com/raycast/script-commands/issues/937#issuecomment-2124224710):

> we run the scripts as a subprocess

**Comment by dehesa** [comment]
Hey @VladimirFokow, very sorry it took so long to get back to you.
The code spawning the process is part of the swift close-source app. We don't do anything special there. Let me copy the extract of how we set it up (it is in Swift):

```swift
let process = Process()
process.qualityOfService = qos.asQualityOfService
process.executableURL = URL(fileURLWithPath: command.scriptPath)

var environment = ProcessInfo.processInfo.environment
let defaultPath = "/usr/local/bin:/opt/homebrew/bin"
if let path = environment["PATH"] {
  environment["PATH"] = defaultPath + ":\(path)"
} else {
  environment["PATH"] = defaultPath
}
environment["LANG"] = "\(Locale.preferredIdentifier ?? Locale.autoupdatingCurrent.identifier).UTF-8"
let proxySettings = UserDefaults.standard.useSystemInternetProxySettings ? InternetProxySettings.fromSystem() : InternetProxySettings.fromEnvironment()
environment.merge(proxySettings.toEnvVars()) { $1 }
process.environment = environment
if !arguments.isEmpty {
  process.arguments = arguments
}

if let currentDirectoryPath = command.currentDirectoryPath {
  if currentDirectoryPath.hasPrefix("/") || currentDirectoryPath.hasPrefix("~") {
    process.currentDirectoryPath = currentDirectoryPath
  } else {
    let scriptDirURL = URL(fileURLWithPath: command.scriptPath).deletingLastPathComponent()
    process.currentDirectoryPath = scriptDirURL.appendingPathComponent(currentDirectoryPath).standardizedFileURL.path
  }
} else {
  process.currentDirectoryPath = URL(fileURLWithPath: command.scriptPath).deletingLastPathComponent().path
}
```

**Comment by dehesa** [comment]
I will be closing this for now, but feel free to open it.
