### ISSUE TITLE
System "dismiss-notifications" script command doesn't work on MacOS Sequoia version 15.1 

### ISSUE THREAD

**Issue by kg345** [raycast/script-commands#967]
Running the script [here](https://github.com/raycast/script-commands/blob/master/commands/system/dismiss-notifications.applescript) results in a 

> Reason: /Users/myusername/Documents/raycast-scripts/test.applescript:753:759: execution error: System Events got an error: Can’t get scroll area 1 of group 1 of window "Notification Center" of process "NotificationCenter". Invalid index. (-1719)
Domain: scripts
Time: 16:41:27.117

Same error regardless if I group or do not group my notifications.

If I edit the script to see what actions/groups exists - I see there's:
- 1 group for window "notification center"
- 1 UI element for the group in the window
    - no actions available in the ui element

**Comment by unnamedd** [comment]
I don't think this is a problem on macOS Sequoia, since the way `NotificationCenter`/`NotificationCentre`/`Notification Center` may differ from one version of English to another. If I am not mistaken, in British English, it will be `NotificationCentre`. 

Perhaps you can check one of those options and change it for yourself. Also, you can search through the issues because we have already discussed that in the past in the issues/PRs.

**Comment by kg345** [comment]
Thanks. I do see these PRs discussing some issues (localization you mentioned, other mentioning that the center needs to be open to work).

https://github.com/raycast/script-commands/pull/917
https://github.com/raycast/script-commands/pull/919

I think the issue, for me, isn't related to localization - as it is _finding_ the NotificationCenter process/window - there's just nothing to do, in terms of actions, within it so not sure there's actually a way to get this to work. I suspect the issue is likely that the "clear" or "clear all" notifications button only appears when you hover on it with your mouse.

Considering the above, I was curious if this script then worked for anyone at any point (and whether that was a prior version of macOS).

**Comment by unnamedd** [comment]
Very good point. 
It will be quite complicated to know if it worked for anyone other than the author himself.

However, I don't really think there will be a final solution that works for everyone. I do think that for those whose computers the script doesn't work on, the best solution would probably be to make some changes to make it work for themselves. Perhaps this is going to be your situation, Kris.

**Comment by kg345** [comment]
Does sound like it probably should be named with `template` to indicate it probably wont' work out of the box for everyone.

For anyone else stumbling on this - this [gist discussion](https://gist.github.com/lancethomps/a5ac103f334b171f70ce2ff983220b4f) does have some working scripts (in particular, [this one](https://gist.github.com/lancethomps/a5ac103f334b171f70ce2ff983220b4f?permalink_comment_id=5198730#gistcomment-5198730) works for me though it loops through each item so can be a bit slow).

**Comment by unnamedd** [comment]
@kg345,

Even though I understand your point about using the `.template`, it doesn't really fit with the idea of it. 
Templates are used when the user needs to make changes to the Script Command right before its use. 
As this is something that would work for a large number of people using English as their main system language, it won't require any extra changes. For others, it would be interesting to add some instructions in the Script Command itself (perhaps a troubleshooting comment) mentioning that if it doesn't work, the user would need to make certain changes.

**Comment by third774** [comment]
Just chiming in to say that this script **did** work for me until I upgraded to Sequoia.

**Comment by giedreblekaite** [comment]
Hey, we have this PR #973 which seems to be fixing the problem just fine, maybe it does to you too?
