### ISSUE TITLE
The short text on inline mode is truncated by an ellipsis

### ISSUE THREAD

**Issue by Urie96** [raycast/script-commands#968]
![image](https://github.com/user-attachments/assets/c4faea37-5e83-4f58-a032-d57c3edfdf28)

**Comment by unnamedd** [comment]
This is not a Script Command issue; therefore, it must be reported on [Raycast Community](https://raycast.com/community) (in the #bugs channel) or via the Send Feedback form (in the root search of Raycast).

With that being said, I am closing this issue. If you do have any questions, please don't hesitate to comment on this issue.
