### ISSUE TITLE
Feature Request: Differentiate Between Left and Right Modifier Keys for Hotkeys

### ISSUE THREAD

**Issue by mizagog** [raycast/script-commands#974]
**Description:**

I would like to request the ability to assign different hotkeys based on whether the left or right modifier keys (e.g., Command, Option, Control) are pressed. Currently, Raycast treats these keys interchangeably, which limits the number of unique hotkeys users can configure. Introducing this distinction could significantly enhance hotkey flexibility and personalization.

**Examples of Use Cases:**

1. **Command Customization:**  
   - Assign `Left Command + K` to open the "Search in Raycast" command.  
   - Assign `Right Command + K` to trigger a system-wide "Quick Note" feature.  

2. **Option Key Differentiation:**  
   - Use `Left Option + S` to run a script for saving a file to a specific folder.  
   - Use `Right Option + S` to open a settings menu for customizing the save location.  

3. **Productivity Workflows:**  
   - Configure `Left Control + T` to open a specific task list.  
   - Configure `Right Control + T` to toggle time tracking.  

**Benefits:**

- Allows users to map more functions without additional key combinations.  
- Enhances workflows by providing granular control over hotkey behavior.  
- Makes Raycast more versatile for power users with complex productivity setups.  

**Technical Considerations:**

- Support for differentiating left and right keys could align with existing operating system APIs that recognize these distinctions (e.g., macOS and Windows).  
- Users could optionally enable this feature in the settings to avoid complexity for those who don’t need it.  

**Conclusion:**

Adding this capability would greatly improve Raycast's hotkey system and empower users to customize their workflows further. Thank you for considering this enhancement, and I’m happy to provide additional examples or clarification if needed!

**Comment by giedreblekaite** [comment]
I've recorded your feature request internally so it's something we can pick up in the future if there's more demand for it. Thank you!
